In [1]:
#### run combined df again if any code changes occur (symbol change) including additions

In [2]:
#### combines 7 days delivery files
#### reads market cap from screener
#### reads averages

#### this reads non_fno_wl, yymmdd_volume_3x_wl, yymmdd_tview_wl_above_500, yymmdd_tview_wl_below_500, sme_csv
 

#### heading for reports
#### title for reports

In [3]:
# importing necessary modules 

import os
import pandas as pd
import csv
from pathlib import Path

base_folder = Path.cwd()
print(base_folder)

C:\Users\sarda\Dropbox\SQL Stock Market Data\Python Code from ChatGPT

In [4]:
###  datapath for lenovo desktop

master_file_dir = Path.joinpath(base_folder, "Master File")

master_file_path = Path.joinpath(base_folder, "Master File", "CompanyMaster.csv")
directory = Path.joinpath(Path(base_folder).parents[0], "Data Files")
combined_directory =  Path.joinpath(Path(base_folder).parents[0], "Delivery Price Combined Files")


input_path =  Path.joinpath(base_folder, "Input File")
output_path = Path.joinpath(base_folder, "Output File")
report_path = Path.joinpath(base_folder,"PDF Reports")

In [5]:
column_order = ['NSE_Code','BSE_Code','Date','NSE_Delivery','BSE_Delivery']


non_fno_csv = os.path.join(output_path, '0_non_fno.csv')
fno_csv = os.path.join(output_path, 'fno.csv')
sme_csv = os.path.join(output_path, 'sme_csv.csv')

avgs_file = os.path.join(input_path, 'NSE BSE Averages.xlsx')

In [6]:
def find_corresponding_codes(master_file_path, user_input):
    nse_code = ""
    bse_code = ""
    co_name = ""

    user_input = user_input.lower()  # Convert user input to lowercase for comparison

    with open(master_file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if row[1].lower() == user_input:  # NSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                co_name = row[0]
                break
            elif row[2].lower() == user_input:  # BSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                co_name = row[0]
                break

    return nse_code, bse_code,co_name

def format_value(value):
    return '{:,.0f}'.format(value)

def format_decimal(x):
    return '{:,.2f}'.format(x)

def averages(scrip_code):
    ema10 = [0]  # Default value for ema10
    ema20 = [0]  # Default value for ema20
    ema50 = [0]  # Default value for ema50
    ema200 = [0]  # Default value for ema200
    
    
        
    if type(scrip_code) == int:
        scrip_code = str(scrip_code)
        averages_df = bse_avg_df[bse_avg_df['Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        averages_df = nse_avg_df[nse_avg_df['Name'] == scrip_code]
    
    if not averages_df.empty:
        ema10 = averages_df['ema10'].values.tolist()
        ema20 = averages_df['ema20'].values.tolist()
        ema50 = averages_df['ema50'].values.tolist()
        ema200 = averages_df['ema200'].values.tolist()
    
    return ema10, ema20, ema50, ema200


def get_mktcap(scrip_code):
    
    if type(scrip_code) == int:
        #scrip_code = str(scrip_code)
        scrip_mktcap_df = mktcap_df[mktcap_df['BSE_Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        scrip_mktcap_df = mktcap_df[mktcap_df['NSE_Code'] == scrip_code]
        
    #scrip_mktcap_df.info()
    
    if not scrip_mktcap_df.empty:
        scrip_mktcap = scrip_mktcap_df['Market Capitalization'].values.tolist()
        
    else:
        scrip_mktcap = [0]
    
    return scrip_mktcap


def get_networth(scrip_code):
    
    if type(scrip_code) == int:
        #scrip_code = str(scrip_code)
        scrip_mktcap_df = mktcap_df[mktcap_df['BSE_Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        scrip_mktcap_df = mktcap_df[mktcap_df['NSE_Code'] == scrip_code]
        
    #scrip_mktcap_df.info()
    
    if not scrip_mktcap_df.empty:
        scrip_networth = scrip_mktcap_df['Net worth'].values.tolist()
        
    else:
        scrip_networth = [0]
    
    return scrip_networth
     
    
    
def replace_nse_code(row):
    if pd.isna(row['NSE_Code']) or row['NSE_Code'] == "":
        return row['BSE_Code']
    else:
        return row['NSE_Code']

# Apply the custom function to the NSE_Code column

def list_process(list_name):
    list_name_lower = [item.lower() for item in list_name]
    nse_code_df = combined_df[combined_df['NSE_Code'].str.lower().isin(list_name_lower)]
    
    numeric_list_name = []
    
    for value in list_name:
        if value.isdigit():
            numeric_list_name.append(int(value))
    
    bse_code_df = combined_df[combined_df['BSE_Code'].isin(numeric_list_name)]
    final_code_df = pd.concat([nse_code_df,bse_code_df], ignore_index=True)
    final_code_df['NSE_Code'] = final_code_df.apply(replace_nse_code, axis=1)
    
    final_code_df.sort_values(by=['NSE_Code', 'Date'], ascending=[True, False], inplace=True)
    grouped_df = final_code_df.groupby('NSE_Code')
    
    for name, group in grouped_df:
        
        ema10, ema20, ema50, ema200 = averages(str(name))
        ema_str = "ema10 / ema20 / ema50 / ema200"
    
        print("")
        print(f"Company Name: {group['Company Name'].iloc[0]} (NSE Code: {name}, BSE Code: {group['BSE_Code'].iloc[0]})")
        print(f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}")
        print("")

        # Format the columns before printing
        group['NSE_Delivery'] = group['NSE_Delivery'].apply(lambda x: '{:,.0f}'.format(x))
        group['BSE_Delivery'] = group['BSE_Delivery'].apply(lambda x: '{:,.0f}'.format(x))
        group['Total_Delivery'] = group['Total_Delivery'].apply(lambda x: '{:,.0f}'.format(x))

        # Print the header with column names excluding 'NSE_Code' and 'BSE_Code'
        header = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
    
        # Print the table with manual formatting
        print(f"{'Date':<8}{'NSE_Delivery':>15}{'BSE_Delivery':>15}{'Total_Delivery':>20}{'Price':>15}")
        for _, row in group[header].iterrows():
            print(f"{row['Date']:<8}{row['NSE_Delivery']:>15}{row['BSE_Delivery']:>15}{row['Total_Delivery']:>20}{row['Price']:>15.2f}")

        # Add two blank spaces between groups
        print("\n")
        

    
    return final_code_df
    
    
def list_process_new(list_name, header):
    
    print(header)
    
    for company in list_name:
    # Filter the DataFrame for the current company
    
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
            #print(company)
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]
            #print(company)

        # Check if the DataFrame is not empty
        if not company_data.empty:
            # Extract relevant information
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10,ema20,ema50,ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"
            
            mktcap_value = get_mktcap(nse_code)
            networth_value = get_networth(nse_code)
            
            print(f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap:{mktcap_value[0]:,.0f}, Networth:{networth_value[0]:,.0f})")

            print("")
        
            print(f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}")
            print("")

            # Format and print the specified columns with additional spaces
            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            # Adjust the spacing between columns
            formatted_data_str = formatted_data.to_string(index=False, 
                                                      col_space={'Date':9,
                                                                 'NSE_Delivery':15,
                                                                 'BSE_Delivery':15,
                                                                 'Total_Delivery': 15, 
                                                                 'Price': 10
                                                                 }
                                                        )

            print(formatted_data_str)
            # Add a line break between companies
            print("\n" + "=" * 50 + "\n")
            print("")
        else:
            print(f"No data found for {company}\n")

    
def add_nse_prefix(df, column_name):
    # Create a copy of the DataFrame to avoid SettingWithCopyWarning
    df = df.copy()

    # Add "NSE:" prefix to the specified column
    df.loc[:, column_name] = "NSE:" + df[column_name].astype(str)

    return df

In [7]:
#### reading nse and bse averages
file_path = avgs_file

# Replace 'Sheet1' with the name of the sheet you want to read
#sheet_name = 'Sheet1'
nse_averages = "NSE Averages"
bse_averages = "BSE Averages"

# Read the Excel file into a DataFrame
#df = pd.read_excel(file_path, sheet_name=sheet_name)

#nse_avg_df = pd.read_excel(file_path, sheet_name = nse_averages, dtype=column_width, engine='openpyxl')
nse_avg_df = pd.read_excel(file_path, sheet_name=nse_averages)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace('_T$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace('_Z$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace(' SM$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace(' ST$',"",regex=True)


nse_avg_df['Name'] = nse_avg_df['Name'].str.strip()


bse_avg_df = pd.read_excel(file_path, sheet_name = bse_averages)
bse_avg_df['Code'] = bse_avg_df['Code'].astype(str)


####################reading market cap file

mktcap_file = os.path.join(master_file_dir, 'MarketCap from Screener.csv')
mktcap_df = pd.read_csv(mktcap_file)
mktcap_df['BSE Code'] = mktcap_df['BSE Code'].fillna(0)
mktcap_df['BSE Code'] = mktcap_df['BSE Code'].astype(int)
mktcap_df['NSE Code'] = mktcap_df['NSE Code'].fillna("")

mktcap_df.rename(columns= { 'BSE Code' : 'BSE_Code', 
                          'NSE Code': 'NSE_Code'}, inplace =True)

mktcap_df.loc[mktcap_df['NSE_Code'] == "", "NSE_Code"] = mktcap_df['BSE_Code']

In [8]:

###### combine 7 days price files

no_days = 7

file_names = sorted([file for file in os.listdir(combined_directory) if file.lower().endswith(("CSV","csv"))
                        and file.startswith("combined")], reverse=True)[:no_days]

print(file_names)

count = 1

for file_name in file_names:
    file_path = os.path.join(combined_directory,file_name)
    csv_file_df = pd.read_csv(file_path)
    
    if count == 1:
        combined_df = csv_file_df
    else:
        combined_df = pd.concat([combined_df, csv_file_df], ignore_index=True)
    
    count += 1
    #print(count)

combined_df['BSE_Code'] = combined_df['BSE_Code'].fillna(0)
combined_df['BSE_Code'] = combined_df['BSE_Code'].astype(int)
combined_df['NSE_Code'] = combined_df['NSE_Code'].fillna("")
combined_df['Company Name'] = combined_df['Company Name'].fillna("")
combined_df['NSE_Code'] = combined_df.apply(replace_nse_code, axis=1)

# Assuming your DataFrame is named combined_df
report_date = combined_df['Date'].max()
report_date = str(report_date)

print(report_date)

['combined_240105.csv', 'combined_240104.csv', 'combined_240103.csv', 'combined_240102.csv', 'combined_240101.csv', 'combined_231229.csv', 'combined_231228.csv']
240105

In [9]:
def print_formatted_rows(stock_list, title):
    # Print the header
    header = "Company Name".ljust(35) + "StockCode".ljust(10) + "Close".rjust(10) + "PrevClose".rjust(10) + \
             "MktCap".rjust(10) + "EMA10".rjust(10) + "EMA20".rjust(10) + "EMA50".rjust(10) + "EMA200".rjust(10)
    print(title)
    print("")
    print("")
    print(header)
    print("")
    print("")

    line_counter = 0
    
    for stock in stock_list:
        if stock.isdigit():
            stock_code = int(stock)
            df_row = combined_df[combined_df['BSE_Code'] == stock_code]
        else:
            stock_code = stock.upper()
            df_row = combined_df[combined_df['NSE_Code'] == stock_code]

        if not df_row.empty:
            company_name = df_row['Company Name'].values[0]
            stock_code = df_row['NSE_Code'].values[0]
            price = df_row['Price'].values[0]
            prevclose = df_row['PrevClose'].values[0]

            ema10, ema20, ema50, ema200 = averages(stock_code)
            ema10 = ema10[0]
            ema20 = ema20[0]
            ema50 = ema50[0]
            ema200 = ema200[0]

            mktcap_value = get_mktcap(stock_code)
            mktcap = mktcap_value[0]

            # Format the values with ljust and rjust
            formatted_row = company_name.ljust(35) + str(stock_code).ljust(10) + \
                             f"{price:.2f}".rjust(10) + f"{prevclose:.2f}".rjust(10) + \
                             f"{mktcap:,.0f}".rjust(10) + f"{ema10:.2f}".rjust(10) + \
                             f"{ema20:.2f}".rjust(10) + f"{ema50:.2f}".rjust(10) + f"{ema200:.2f}".rjust(10)

            print(formatted_row)
            
            line_counter += 1

            # Insert a blank line after every 5 lines
            if line_counter % 5 == 0:
                print()

In [10]:
### reading csv of top 50 by value and volume in delivery

non_fno_df_in = pd.read_csv(non_fno_csv)
fno_df = pd.read_csv(fno_csv)
sme_df_in = pd.read_csv(sme_csv)

"""It fills the missing (NaN) values in the 'NSE_Code' column of the DataFrame non_fno_df with values 
from the 'BSE_Code' column converted to strings.

The .astype(str) part is used to convert the values in the 'BSE_Code' column to strings. 
This is necessary because the 'NSE_Code' column likely contains strings (object dtype), and 
you need to ensure that the replacement values are of the same data type.

The fillna method is used to perform the filling operation. By setting the inplace parameter to True, 
the operation is performed directly on the DataFrame without the need to assign the result back to the DataFrame."""


def fill_missing_nse_code(data_frame):
    # Convert non-finite 'BSE_Code' values to integers while replacing NaN with a placeholder
    placeholder_int = -1  # Placeholder integer value for NaN
    data_frame['BSE_Code'] = data_frame['BSE_Code'].fillna(placeholder_int).astype(int)
    
    # Convert 'BSE_Code' values to strings and fill missing 'NSE_Code' values
    data_frame['NSE_Code'].fillna(data_frame['BSE_Code'].astype(str), inplace=True)

    return data_frame


non_fno_df = fill_missing_nse_code(non_fno_df_in)
sme_df = fill_missing_nse_code(sme_df_in)

#non_fno_df['NSE_Code'].fillna(non_fno_df['BSE_Code'].astype(int).astype(str), inplace=True)
#sme_df['NSE_Code'].fillna(sme_df['BSE_Code'].astype(int).astype(str), inplace=True)

# Get the unique 'NSE_Code' values as a list
unique_non_fno = non_fno_df['NSE_Code'].unique().tolist()
sme_list = sme_df['NSE_Code'].unique().tolist()

focus_list = [ '531112', '538734', '543953', '543971', 'adanipower', 'amber', 'anantraj', 'angelone', 'anup', 'apollo', 
           'arvind', 'arvindfasn', 'bajajhind', 'bclind', 'bluejet', 'bluestarco', 'brigade', 'bse', 'cdsl', 'chembond', 
           'cignititec', 'creditacc', 'cupid', 'daawat', 'dbrealty', 'dharmaj', 'diamondyd', 'elecon', 'electcast', 
           'emil', 'focus', 'gabriel', 'gensol', 'genuspower', 'hblpower', 'hirect', 'hitech', 'hpl', 'idea', 'hcc',
           'ifglexpor', 'iiflsec', 'ikio', 'indotech', 'inoxwind', 'jindalsaw', 'jkcement', 'jklakshmi', '530129',
           'jktyre', 'jpassociat', 'jppower', 'jwl', 'kapston', 'kesoramind', 'kpittech', 'l&tfh', 'lalpathlab', 'tv18brdcst',
           'lodha', 'marine', 'mblinfra', 'mcx', 'newgen', 'paytm', 'peninland', 'pfs', 'repcohome','ndrauto','magson',
           'phoenixltd', 'pplpharma', 'premexpln', 'prestige', 'pyramid', 'radico', 'rategain', 'recltd', '522101',
           'rkforge', 'rpglife', 'sadhnaniq', 'sanghvimov', 'satin', 'sdbl', 'senco', 'sepc', 'shriramfin','shrirampps', 
            'skygold', 'solarinds', 'sonatsoftw', 'spandana', 'suzlon', 'tatamotors', 'thomascook', 'shripiston',
           'titagarh', 'tril', 'unionbank', 'vijaya', 'walchannag', 'welspunind', 'zaggle', 'zeemedia', 'zomato',
           'hariompipe', 'semac', 'tci', '540358', 'icil', '20microns', 'prsmjohnsn', 'poonawalla', 'cello', 'hcc', 
          'bikaji', 'neulandlab', 'jppower', 'trent']

In [11]:
dely_3x = os.path.join(output_path, f'_{report_date}_0_volume_3x_wl.csv')
dely_3x_df = pd.read_csv(dely_3x)
dely_3x_df.head()

         Symbol
0     NSE:KCEIL
1      NSE:KIMS
2    NSE:360ONE
3  NSE:MIRZAINT
4    NSE:VLEGOV

In [12]:

#dely_3x_list = dely_3x_df.tolist()
# Extract the 'ScripCode' column from the DataFrame
dely_3x_list = dely_3x_df['Symbol'].tolist()

cleaned_list = [stock.replace('NSE:', '') for stock in dely_3x_list]
dely_3x_list = cleaned_list

# Extract the first 50 records of the 'ScripCode' column from the DataFrame
#dely_3x_list = dely_3x_df['ScripCode'].head(50).tolist()

#dely_3x_list

In [13]:
### above 500 cr

# percent_new_high = os.path.join(output_path, f'_{report_date}_0_tview_wl_above_500.csv')
#percent_new_high =r"C:\Users\birap\OneDrive\Desktop\Tradeview\tradingView\Python code for chatGpt\Output File\_231221_0_tview_wl_above_500.csv"
#percent_new_high_df = pd.read_csv(percent_new_high)

percent_new_high = os.path.join(output_path,f'_{report_date}_1_tview_wl_above_500.csv')
percent_new_high_df = pd.read_csv(percent_new_high)

#percent_new_high_df.head()

percent_new_high_df.head()

           Ticker
0    NSE:ALOKINDS
1    NSE:MIRZAINT
2    NSE:KRITINUT
3    NSE:SUBEXLTD
4  NSE:SUNDARMHLD

In [14]:
# Replace "NSE:" with an empty string in the 'Ticker' column
percent_new_high_df['Ticker'] = percent_new_high_df['Ticker'].str.replace('NSE:', '')

# Assuming percent_new_high_df is your DataFrame

# Replace "NSE:" with an empty string in the 'Ticker' column
percent_new_high_df['Ticker'] = percent_new_high_df['Ticker'].str.replace('NSE:', '')

# Print the updated DataFrame
#print(percent_new_high_df)

# Convert the 'Ticker' column to a list
ticker_list = percent_new_high_df['Ticker'].tolist()

#print(ticker_list)


#### below 500 cr

# percent_below = os.path.join(output_path, f'_{report_date}_0_tview_wl_below_500.csv')

# percent_below_df = pd.read_csv(percent_below)
#percent_below = r"C:\Users\birap\OneDrive\Desktop\Tradeview\tradingView\Python code for chatGpt\Output File\_231221_0_tview_wl_below_500.csv"
#percent_below_df = pd.read_csv(percent_below)

percent_below = os.path.join(output_path,f'_{report_date}_2_tview_wl_below_500.csv')
percent_below_df = pd.read_csv(percent_below)

In [15]:
percent_below_df.head()

           Ticker
0     NSE:ALMONDZ
1         NSE:IVP
2  NSE:DAMODARIND
3    NSE:SHRITECH
4       NSE:YAARI

In [16]:
percent_below_df['Ticker'] = percent_below_df['Ticker'].str.replace("NSE:","")
ticker_below = percent_below_df["Ticker"].tolist()

In [18]:
import openpyxl

file_path = "C:\\Users\\sarda\\Dropbox\\TS Personal\\Trade Files\\Consolidated Trade File from 1st April 2022.xlsx"
def read_sheet_pivots(file_path, sheet_name):
    data = []
    workbook = openpyxl.load_workbook(file_path, read_only=True)
    sheet = workbook[sheet_name]
    
    row_number = 28
    column_m = 'M'
    column_n = 'N'
    
    
    while True:
        cell_m = sheet[column_m + str(row_number)].value
        cell_n = sheet[column_n + str(row_number)].value
        
        if cell_m is None and cell_n is None:
            break
        
        # Convert the cell values to strings and store them in the list
        if cell_m is not None:
            m_value = str(cell_m)
            if m_value != '0' and (not m_value.isdigit() or m_value.startswith('5')):
                data.append(m_value)
        
        if cell_n is not None:
            n_value = str(cell_n)
            if n_value != '0' and (not n_value.isdigit() or n_value.startswith('5')):
                data.append(n_value)
        
        row_number += 1
    
    return data

# Example usage

sheet_name = 'Pivots'
holding_list = read_sheet_pivots(file_path, sheet_name)
print(holding_list)


##saving the holdings to csv for uploading to chartink and trading view

# Specify the name of the CSV file you want to create
#csv_file_name = output_path + "0 My_Holdings.csv"
csv_file_name = os.path.join(output_path, "0 My_Holdings.csv")


# Write the data to the CSV file
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Company"])  # Optional: Write a header row
    writer.writerows([[item] for item in holding_list])

['UJJIVANSFB', 'REMSONSIND', 'MARINE', 'ICICIBANK', 'SATIN', 'KSOLVES', 'IBREALEST', 'JMFINANCIL', 'MANKIND', 'NFL', 'ISGEC', 'BLKASHYAP', 'L&tfh', 'SHYAMMETL', 'IWEL', 'INDIGOPNTS', 'NATIONALUM', 'JTLIND', 'MAGSON', 'KOTAKBANK', 'ARVINDFASN', 'PRIMESECU', 'ARSHIYA', '543597', 'EIHOTEL', 'MUFTI', 'LEMONTREE', '#N/A', '#N/A', 'INOXWIND', 'HBLPOWER', 'MEDPLUS', '#N/A', '#N/A', 'SIGNATURE', '542753', 'CHEMPLASTS', 'GOCOLORS', '531968', 'MANPASAND']

In [44]:
heading_non_fno = "          Top 50 7-day deliveries non_fno " + report_date
heading_sme = "          Top 50 7-day deliveries sme " + report_date

heading_3_percent = "          7-day deliveries up_3_percent or new_highs above 500 cr " + report_date
heading_3_percent_below = "          7-day deliveries up_3_percent or new_highs below 500 cr " + report_date

heading_3x = "          7-day deliveries 3x dely volume " + report_date
heading_holding = "          7-day deliveries for holdings " + report_date

heading_above_10k = "          7-day deliveries mktcap above 10k cr " + report_date
heading_below_1000 = "          7-day deliveries mktcap below 1000 cr " + report_date
heading_1k_10k = "            7-day deliveries mktcap 1k - 10k cr " + report_date
###############################################
###############################################

heading_non_fno = "          3. Top 50 7-day deliveries non_fno " + report_date
heading_sme = "          4. Top 50 7-day deliveries sme " + report_date

heading_3_percent = "          1. 7-day deliveries up_3_percent or new_highs above 500 cr " + report_date
heading_3_percent_below = "          5. 7-day deliveries up_3_percent or new_highs below 500 cr " + report_date

heading_3x = "          2. 7-day deliveries 3x dely volume " + report_date
heading_holding = "          7-day deliveries for holdings " + report_date

heading_above_10k = "          7-day deliveries mktcap above 10k cr " + report_date
heading_below_1000 = "          7-day deliveries mktcap below 1000 cr " + report_date
heading_1k_10k = "            7-day deliveries mktcap 1k - 10k cr " + report_date

In [45]:
title_non_fno = "Non_fno top deliveries " + report_date + " with averages"
title_sme = "SME top deliveries " + report_date + " with averages"

title_3_percent = "         up_3_percent or new_highs above 500 cr " + report_date + " with averages"
title_3_percent_below = "         up_3_percent or new_highs below 500 cr " + report_date + " with averages"

title_3x = "          3x dely volume deliveries " + report_date + " with averages"
title_holding = "          7-day deliveries for holdings " + report_date + " with averages"

title_above_10k = "         Top deliveries mktcap above 10k cr " + report_date + " with averages"
title_below_1000 = "         Top deliveries mktcap below 1000 cr " + report_date + " with averages"
title_1k_10k = "          Top deliveries mktcap 1k - 10k cr " + report_date + " with averages"

####################################################################
#############################################################

title_non_fno = " 3. Non_fno top deliveries " + report_date + " with averages"
title_sme = " 4.SME top deliveries " + report_date + " with averages"

title_3_percent = "         1. up_3_percent or new_highs above 500 cr " + report_date + " with averages"
title_3_percent_below = "         5. up_3_percent or new_highs below 500 cr " + report_date + " with averages"

title_3x = "          2. 3x dely volume deliveries " + report_date + " with averages"
title_holding = "          7-day deliveries for holdings " + report_date + " with averages"

title_above_10k = "         Top deliveries mktcap above 10k cr " + report_date + " with averages"
title_below_1000 = "         Top deliveries mktcap below 1000 cr " + report_date + " with averages"
title_1k_10k = "          Top deliveries mktcap 1k - 10k cr " + report_date + " with averages"

In [46]:
ticker_list

['ALOKINDS',
 'MIRZAINT',
 'KRITINUT',
 'SUBEXLTD',
 'SUNDARMHLD',
 'GEPIL',
 'SULA',
 'AMNPLST',
 'DISHTV',
 'ADSL',
 'DIGISPICE',
 'BCLIND',
 'URJA',
 'RAJMET',
 'ENDURANCE',
 'SPARC',
 'FINPIPE',
 'KOTHARIPRO',
 'CREDITACC',
 'SHYAMCENT',
 'OLECTRA',
 'BEML',
 'HITECH',
 'SWANENERGY',
 'INDORAMA',
 'TRIDENT',
 'EXPLEOSOL',
 'FINOPB',
 'TRIL',
 'PPL',
 'EXXARO',
 'BASILIC',
 'SBGLP',
 'AXITA',
 'TVTODAY',
 'PAISALO',
 'IGARASHI',
 'STERTOOLS',
 'MSUMI',
 'DBCORP',
 'HSCL',
 'DBREALTY',
 'CHEMBOND',
 'KCP',
 'RTNINDIA',
 'TIINDIA',
 'ELECTCAST',
 'PHOENIXLTD',
 'ALBERTDAVD',
 'APLAPOLLO',
 'HPL',
 'E2E',
 'VISHNUINFR',
 'CUPID',
 'INDOTECH',
 'VERTOZ',
 'KILITCH',
 'GOLDTECH',
 'MOTISONS',
 'RBZJEWEL',
 'UNITECH',
 'AHLUCONT',
 'GVKPIL',
 'SUZLON',
 'SWELECTES',
 'MANINDS',
 'BUTTERFLY',
 'SAHANA',
 'IONEXCHANG',
 'HIRECT',
 'CENTRUM',
 'ANGELONE',
 'RTNPOWER',
 'ASHAPURMIN',
 'ISEC',
 'INDIAGLYCO',
 'GENESYS',
 'HMVL',
 'NHPC',
 'NAVKARCORP',
 'ALLETEC',
 'SUKHJITS',
 'BSOFT',
 'VISAKAIND',
 'FOODSIN',
 'SIRCA',
 'SIMPLEXINF',
 'POLYMED',
 'JCHAC',
 'LAXMIMACH',
 'JWL',
 'SCHAEFFLER',
 'WSI',
 'GULPOLY',
 'MACPOWER',
 'VMART',
 'DPABHUSHAN',
 'GTLINFRA',
 'RPOWER',
 'KUANTUM',
 'HAL',
 'UDS',
 'BDL',
 'YESBANK',
 'TIPSINDLTD',
 'NH',
 'IBREALEST',
 'NAUKRI',
 'KAJARIACER',
 'BALKRISIND',
 'NETWORK18',
 'JYOTHYLAB',
 'ANANTRAJ',
 'SHALPAINTS',
 'AWHCL',
 'ACCELYA',
 'SBCL',
 'HERANBA',
 'KHADIM',
 'ASTERDM',
 'PARACABLES',
 'GLAXO',
 'CESC',
 'OFSS',
 'SIGNATURE',
 'ADANIPORTS',
 'ZOMATO',
 'EQUITASBNK',
 'BIOCON',
 'ARVSMART',
 'ONEPOINT',
 'INDUSTOWER',
 'GMDCLTD',
 'ARTEMISMED',
 'HATHWAY',
 'UNOMINDA',
 'JAIBALAJI',
 'IIFLSEC',
 'GODREJIND',
 'FSL',
 'DCBBANK',
 'FOCUS',
 'RAINBOW',
 'DHANUKA',
 'DOLPHIN',
 'PPLPHARMA',
 'HINDCOPPER',
 'POONAWALLA',
 'KPIL',
 'IPL',
 'V2RETAIL',
 'GODREJCP',
 'SOLARA',
 'EXIDEIND',
 'BEDMUTHA',
 'KSB',
 'GODREJPROP',
 'SNOWMAN',
 'IOC',
 'SHRIRAMFIN',
 'SPANDANA',
 'JUBLPHARMA',
 'HTMEDIA',
 'CENTURYTEX',
 'KEI',
 'MEGASOFT',
 'BIKAJI',
 'AXISCADES',
 'MRF',
 'BOSCHLTD',
 'ISGEC',
 'TATAPOWER',
 'ONGC',
 'JSL',
 'MGL',
 'THERMAX',
 'SANOFI',
 'HEMIPROP',
 'CYBERTECH',
 'CHOICEIN',
 'BRNL',
 'BHARATFORG',
 'AUROPHARMA',
 'LICHSGFIN',
 'IRCTC',
 'AUBANK',
 'THEMISMED',
 'SIGACHI',
 'ORIENTCEM',
 'BANKINDIA',
 'GREENPANEL',
 'PFIZER',
 'DYNAMATECH',
 'JPASSOCIAT',
 'SANSERA',
 'GSPL',
 'TATACOFFEE',
 'MRPL',
 'POWERGRID',
 'BHARTIARTL',
 'TITAN',
 'UBL',
 'EIDPARRY',
 'TATACONSUM',
 'SALASAR',
 'MANAPPURAM',
 'NMDC',
 'VENUSREM',
 'AURIONPRO',
 'NEWGEN',
 'BEL',
 'ALKEM',
 'POWERINDIA',
 'LODHA',
 'TATAMOTORS',
 'CLSEL',
 'GMRINFRA',
 'NTPC',
 'LUPIN',
 'CANBK',
 'DIAMONDYD',
 'RELINFRA',
 'JPPOWER',
 'TRU',
 'SAKAR',
 'OBEROIRLTY',
 'RALLIS',
 'SAKUMA',
 'DLF',
 'MUTHOOTFIN',
 'KIRLOSENG',
 'AMBUJACEM',
 'SHRIRAMPPS',
 'MTNL',
 'INDHOTEL',
 'DEEPENR',
 'CELLO',
 'KALYANKJIL',
 'RUSTOMJEE',
 'GPIL',
 'THEINVEST',
 'CAPACITE',
 'STAR',
 'PRINCEPIPE',
 'TATACHEM',
 'PENIND',
 'CHOLAFIN',
 'VLEGOV',
 'GALLANTT',
 'ACCENTMIC']

In [24]:
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

def create_table_with_header(df, add_column_names=False, table_width=None):
    """create a table with header and data"""
    table_data = [df.columns.tolist()] + df.values.tolist()
        
    style = [
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),  # Left align first column
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),  # Right align remaining columns
        ('FONTSIZE', (1, 1), (-1, -1), 9),
        ('LEADING', (0, 0), (-1, -1), 8),  # Set leading for all cells to a smaller value
    ]

    t = Table(table_data, repeatRows=1, colWidths=[100, 80, 80, 80, 60])
    column_header_style = [('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTSIZE', (1, 1), (-1, -1), 9),
                        ]
    
    t.setStyle(column_header_style)
    t.setStyle(style)
    
    # Remove table borders
    t.setStyle([('LINEBELOW', (0, 0), (-1, 0), 0, colors.white),  # Hide line below header
                ('GRID', (0, 0), (-1, -1), 0, colors.white)])      # Hide grid lines
    
    return t

def add_headers_and_footers(canvas, doc):
    """Add header and footer here"""
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    footer_style = getSampleStyleSheet()['Normal']
    footer_style.alignment = 1  # 0=Left, 1=Center, 2=Right
    
    footer = Paragraph(text, footer_style)
    w, h = footer.wrap(doc.width, doc.bottomMargin - 10)  # Adjusted bottom margin
    footer.drawOn(canvas, doc.leftMargin, doc.bottomMargin - h)

    # Change title text color to white for pages after the first one
    if page_num > 1:
        title_style = getSampleStyleSheet()['Title']
        title_style.textColor = colors.white

def list_process_to_pdf(list_name, header, output_path):
    left_margin = 20
    right_margin = 20
    top_margin = 10
    bottom_margin = 20  # Add a bottom margin
    page_width = A4[0]  # Get width from letter page size
    page_height = A4[1] - top_margin - bottom_margin # Adjust height for margins

    # Create a SimpleDocTemplate with adjusted page size and margins
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=(page_width, page_height),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin
    )

    company_no = 1
    # Create a list to hold all elements
    elements = []
    
    # header
    styles = getSampleStyleSheet()
    h2_style = styles['Title']
    h2_style.fontSize = 10
    h2_style.Name = 'Arial'
    h2_style.leading = 9
    main_title = Paragraph(header, h2_style)
    elements.extend([main_title])
    for company in list_name:
        # to adjust only 5 company in a single page
        if company_no > 5:
            company_no = 1
            elements.extend([PageBreak()])
        company_no +=1
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]
        if not company_data.empty:
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10, ema20, ema50, ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"

            mktcap_value = get_mktcap(nse_code)
            styles = getSampleStyleSheet()

            # adding company info to pdf
            txt = f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap: {mktcap_value[0]:,.0f})"
            h2_style = styles['Normal']
            h2_style.fontSize = 9
            h2_style.bold = True
            h2_style.alignment = 0
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])

            # ema values
            txt =f"{ema_str} == {ema10[0]}    {ema20[0]}    {ema50[0]}    {ema200[0]}"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
            # adding space
            elements.extend([Spacer(1, 24)])
            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            formatted_data_str = formatted_data.to_string(index=False, col_space={'Date': 9, 'NSE_Delivery': 15, 'BSE_Delivery': 15,
                                                                                   'Total_Delivery': 15, 'Price': 10})
            table_width = doc.width - doc.leftMargin - doc.rightMargin
            table = create_table_with_header(formatted_data, add_column_names=True, table_width=table_width)
            elements.append(table)
            # adding space
            elements.extend([Spacer(0.5, 24)])
        else:
            txt=f"No data found for {company}\n"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
        
    doc.build(elements, onFirstPage=add_headers_and_footers, onLaterPages=add_headers_and_footers)

In [25]:
def format_price(value):
    return f"{value:.2f}" if not pd.isna(value) else ""

def format_prevclose(value):
    return f"{value:.2f}" if not pd.isna(value) else ""

def format_mktcap(value):
    return f"{value:,.0f}" if not pd.isna(value) else ""

def format_ema(value):
    return f"{value:.2f}" if not pd.isna(value) else ""

def get_formatted_dataframe(stock_list):
    results_df = pd.DataFrame(columns=['Company Name', 'NSE Code', 'Price', 'PrevClose', 'MktCap', 'EMA10', 'EMA20', 'EMA50', 'EMA200'])

    for stock in stock_list:
        if stock.isdigit():
            stock_code = int(stock)
            df_row = combined_df[combined_df['BSE_Code'] == stock_code]
        else:
            stock_code = stock.upper()
            df_row = combined_df[combined_df['NSE_Code'] == stock_code]

        if not df_row.empty:
            company_name = df_row['Company Name'].values[0]
            stock_code = df_row['NSE_Code'].values[0]
            price = df_row['Price'].values[0]
            prevclose = df_row['PrevClose'].values[0]

            ema10, ema20, ema50, ema200 = averages(stock_code)
            ema10 = ema10[0]
            ema20 = ema20[0]
            ema50 = ema50[0]
            ema200 = ema200[0]

            mktcap_value = get_mktcap(stock_code)
            mktcap = mktcap_value[0]

            # Format the values with ljust and rjust
            row_df = pd.DataFrame({
                'Company Name': company_name,
                'NSE Code': stock_code,
                'Price': price,
                'PrevClose': prevclose,
                'MktCap': mktcap,
                'EMA10': ema10,
                'EMA20': ema20,
                'EMA50': ema50,
                'EMA200': ema200
            }, index=[0])
            
            row_df['Company Name'] = row_df['Company Name'].str.ljust(35)
            row_df['NSE Code'] = row_df['NSE Code'].astype(str).str.ljust(10)
            row_df['Price'] = row_df['Price'].map('{:.2f}'.format).str.rjust(10)
            row_df['PrevClose'] = row_df['PrevClose'].map('{:.2f}'.format).str.rjust(10)
            row_df['MktCap'] = row_df['MktCap'].map('{:,.0f}'.format).str.rjust(10)
            row_df['EMA10'] = row_df['EMA10'].map('{:.2f}'.format).str.rjust(10)
            row_df['EMA20'] = row_df['EMA20'].map('{:.2f}'.format).str.rjust(10)
            row_df['EMA50'] = row_df['EMA50'].map('{:.2f}'.format).str.rjust(10)
            row_df['EMA200'] = row_df['EMA200'].map('{:.2f}'.format).str.rjust(10)

            # Concatenate the row_df to results_df
            results_df = pd.concat([results_df, row_df], ignore_index=True)

    return results_df

def create_table_with_header_formatted(df, add_column_names=False, table_width=None):
    """create a table with header and data"""
    table_data = [df.columns.tolist()] + df.values.tolist()

    for i in range(6, len(table_data) + 2, 6):  # Include the last possible index
        table_data.insert(i, [''] * len(df.columns))

    style = [
        ('ALIGN', (0, 0), (1, -1), 'LEFT'),  # Left align first two columns
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),  # Right align remaining columns
        ('FONTSIZE', (1, 1), (-1, -1), 9),
        ('LEADING', (0, 0), (-1, -1), 8),  # Set leading for all cells to a smaller value
    ]

    t = Table(table_data, repeatRows=1)
    column_header_style = [('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTSIZE', (1, 1), (-1, -1), 9),
                        ]
    
    t.setStyle(column_header_style)
    t.setStyle(style)
    
    # Remove table borders
    t.setStyle([('LINEBELOW', (0, 0), (-1, 0), 0, colors.white),  # Hide line below header
                ('GRID', (0, 0), (-1, -1), 0, colors.white)])      # Hide grid lines
    
    return t

def print_formatted_rows_pdf(stock_list, title, output_path):
    # Print the header
    left_margin = 20
    right_margin = 20
    top_margin = 10
    bottom_margin = 20  # Add a bottom margin
    page_width = A4[0] + 35 # Get width from letter page size
    page_height = A4[1] - top_margin - bottom_margin # Adjust height for margins

    # Create a SimpleDocTemplate with adjusted page size and margins
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=(page_width, page_height),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin
    )
    
    elements = []
    header = "Company Name".ljust(35) + "StockCode".ljust(10) + "Close".rjust(10) + "PrevClose".rjust(10) + \
             "MktCap".rjust(10) + "EMA10".rjust(10) + "EMA20".rjust(10) + "EMA50".rjust(10) + "EMA200".rjust(10)
    
    # add title
    formatted_df = get_formatted_dataframe(stock_list=stock_list)

    styles = getSampleStyleSheet()
    h2_style = styles['Title']
    h2_style.fontSize = 10
    h2_style.Name = 'Calibri'
    h2_style.leading = 9
    h2_style.alignment = 1  # 0=Left, 1=Center, 2=Right
    main_title = Paragraph(title, h2_style)
    elements.extend([main_title])

    # add space
    elements.extend([Spacer(0.5, 24)])

    #add header
    styles = getSampleStyleSheet()
    h2_style = styles['Title']
    h2_style.fontSize = 10
    title = Paragraph(header, style=h2_style)
    table_width = doc.width - doc.leftMargin - doc.rightMargin

    # Add elements for title and table
    records_per_page = 40
    chunks = [formatted_df[j:j + records_per_page] for j in range(0, len(formatted_df), records_per_page)]
    for chunk in chunks:
        elements.extend([title, create_table_with_header_formatted(chunk, add_column_names=True, table_width=table_width), PageBreak()])
        

    doc.build(elements, onFirstPage=add_headers_and_footers, onLaterPages=add_headers_and_footers)

In [50]:
def pdf_report_print(df,pdf_name,report_heading,report_title):
    abc = len(df)
    abc = str(abc)
    report_heading = report_heading + " (" + abc + " scrips)"
    print("")
    print("")
    pdf_dely = os.path.join(base_folder,report_path,f"{report_date}_{pdf_name} {abc} scrips.pdf")
    pdf_averages = os.path.join(base_folder, report_path, f"{report_date}_averages_{pdf_name} {abc} scrips.pdf")
    
    list_process_to_pdf(df,header=report_heading,output_path=pdf_dely)
    print_formatted_rows_pdf(stock_list=df, title=report_title, output_path=pdf_averages)
    
    return

In [53]:
pdf_report_print(ticker_list,"1_3_pc_new_high_above_500", heading_3_percent, title_3_percent)
pdf_dely_3x = pdf_report_print(dely_3x_list,"2_3x_dely", heading_3x,title_3x)
pdf_non_fno = pdf_report_print(unique_non_fno,"3_non_fno", heading_non_fno, title_non_fno)
pdf_sme = pdf_report_print(sme_list,"4_sme",heading_sme,title_sme)
pdf_below_500 = pdf_report_print(ticker_below,"5_3_pc_new_high_below_500", heading_3_percent_below,title_3_percent_below)

In [29]:
abc = len(ticker_list)

print(heading_3_percent,"(",abc," scrips)")
print("")
#print_formatted_rows(ticker_list,title_3_percent)
print()
print()
print()
#list_process_new(ticker_list, heading_3_percent)


pdf_3_percent = os.path.join(base_folder, report_path,f"{report_date}_1_3_pc_new_high_above_500 {abc} scrips.pdf")
pdf_averages = os.path.join(base_folder, report_path,f"{report_date}_averages_1_3_pc_new_high_above_500 {abc} scrips.pdf")


list_process_to_pdf(ticker_list, header=heading_3_percent, output_path=pdf_3_percent)
print_formatted_rows_pdf(stock_list=ticker_list,title=title_3_percent, output_path=pdf_averages)

          1. 7-day deliveries up_3_percent or new_highs above 500 cr 240105 ( 250  scrips)

In [30]:
abc = len(dely_3x_list)
print(heading_3x,"(",abc," scrips)")
#print_formatted_rows(dely_3x_list,heading_3x)
print()
print()
print()

pdf_3_percent = os.path.join(base_folder, report_path,f"{report_date}_2_3x_dely {abc} scrips.pdf")
pdf_averages = os.path.join(base_folder, report_path,f"{report_date}_averages_2_3x_dely {abc} scrips.pdf")


#list_process_new(dely_3x_list, heading_3x)
list_process_to_pdf(dely_3x_list, header=heading_3x, output_path=pdf_3_percent)
print_formatted_rows_pdf(stock_list=dely_3x_list,title=heading_3x, output_path=pdf_averages)

          2. 7-day deliveries 3x dely volume 240105 ( 86  scrips)

In [31]:
abc = len(unique_non_fno)
print(heading_non_fno,"(",abc," scrips)")
print("")
#print_formatted_rows(unique_non_fno,title_non_fno)
print()
print()
print()
#list_process_new(unique_non_fno, heading_non_fno)
pdf_3_percent = os.path.join(base_folder, report_path,f"{report_date}_3_non_fno {abc} scrips.pdf")
pdf_averages = os.path.join(base_folder, report_path,f"{report_date}_averages_3_non_fno {abc} scrips.pdf")


list_process_to_pdf(unique_non_fno, header=heading_non_fno, output_path=pdf_3_percent)
print_formatted_rows_pdf(stock_list=dely_3x_list,title=title_non_fno, output_path=pdf_averages)

          3. Top 50 7-day deliveries non_fno 240105 ( 82  scrips)

In [32]:
abc = len(unique_non_fno)

print(heading_sme,"(",abc," scrips)")
print("")
#print_formatted_rows(sme_list,title_sme)
print()
print()
print()
#list_process_new(sme_list,heading_sme)

pdf_3_percent = os.path.join(base_folder, report_path,f"{report_date}_4_sme {abc} scrips.pdf")
pdf_averages = os.path.join(base_folder, report_path,f"{report_date}_averages_4_sme {abc} scrips.pdf")


list_process_to_pdf(sme_list, header=heading_sme, output_path=pdf_3_percent)
print_formatted_rows_pdf(stock_list=dely_3x_list,title=title_sme, output_path=pdf_averages)

          4. Top 50 7-day deliveries sme 240105 ( 82  scrips)

In [33]:
abc = len(ticker_below)

print(heading_3_percent_below,"(",abc," scrips)")
print("")
#print_formatted_rows(ticker_below,title_3_percent_below)
print()
print()
print()
#list_process_new(ticker_below, heading_3_percent_below)

pdf_3_percent = os.path.join(base_folder, report_path,f"{report_date}_5_3_pc_new_high_below_500 {abc} scrips.pdf")
pdf_averages = os.path.join(base_folder, report_path,f"{report_date}_averages_5_3_pc_new_high_below_500 {abc} scrips.pdf")

list_process_to_pdf(ticker_below, header=heading_3_percent_below, output_path=pdf_3_percent)
print_formatted_rows_pdf(stock_list=ticker_below,title=title_3_percent_below, output_path=pdf_averages)

          5. 7-day deliveries up_3_percent or new_highs below 500 cr 240105 ( 98  scrips)

In [269]:
print_formatted_rows(holding_list,holding_list)
print()
print()
print()
list_process_new(holding_list, holding_list)
list_process_to_pdf(holding_list, header=holding_list, output_path="holding_list.pdf")
print_formatted_rows_pdf(stock_list=holding_list,title=holding_list, output_path=f"{report_date}_fromatted_holding_list.pdf")

NameError: name 'holding_list' is not defined

In [275]:
print_formatted_rows(list_above_10k,title_above_10k)
print()
print()
print()
list_process_new(list_above_10k, heading_above_10k)
list_process_to_pdf(list_above_10k, header=heading_above_10k, output_path="heading_above_10k.pdf")
print_formatted_rows_pdf(stock_list=list_above_10k,title=title_above_10k.strip(), output_path=f"{report_date}_list_above_10k.pdf")

         Top deliveries mktcap above 10k cr 231020 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Adani Power Ltd.                   ADANIPOWER    338.30    344.45   197,823      0.00      0.00      0.00      0.00
Amber Enterprises India Ltd.       AMBER        3036.60   2951.30    10,245      0.00      0.00      0.00      0.00
Angel One Ltd.                     ANGELONE     2343.45   2200.45    27,611      0.00      0.00      0.00      0.00
Bikaji Foods International Ltd     BIKAJI        489.05    491.50    13,823      0.00      0.00      0.00      0.00
Blue Star Ltd.                     BLUESTARCO    919.30    944.25    19,465      0.00      0.00      0.00      0.00

Brigade Enterprises Ltd.           BRIGADE       611.70    614.60    19,992      0.00      0.00      0.00      0.00
BSE Ltd.                           BSE          1587.80   1537.60    31,280      0.00      0.00      0.00      0.00
Central Depository Services (I     CDSL         1343.15   1339.50    19,343      0.00      0.00      0.00      0.00
Concord Biotech                    CONCORDBIO   1174.55   1185.50    15,715      0.00      0.00      0.00      0.00
CreditAccess Grameen Ltd.          CREDITACC    1389.85   1384.25    25,711      0.00      0.00      0.00      0.00

Elecon Engineering Company Ltd     ELECON        807.15    786.95    10,549      0.00      0.00      0.00      0.00
Vodafone Idea Ltd.                 IDEA           11.75     12.00    65,037      0.00      0.00      0.00      0.00
Jindal Saw Ltd.                    JINDALSAW     397.15    395.95    13,481      0.00      0.00      0.00      0.00
JK Cement Ltd.                     JKCEMENT     3301.65   3345.10    29,238      0.00      0.00      0.00      0.00
Jupiter Wagons Ltd.                JWL           310.45    311.70    13,202      0.00      0.00      0.00      0.00

KPIT Technologies Ltd.             KPITTECH     1195.40   1213.25    41,870      0.00      0.00      0.00      0.00
L&T Finance Holdings Ltd.          L&TFH         137.85    138.15    38,048      0.00      0.00      0.00      0.00
Dr. Lal Pathlabs Ltd.              LALPATHLAB   2511.70   2507.65    21,721      0.00      0.00      0.00      0.00
Macrotech Developers Ltd.          LODHA         815.05    817.00    91,717      0.00      0.00      0.00      0.00
Multi Commodity Exchange Of In     MCX          2320.00   2184.50    16,043      0.00      0.00      0.00      0.00

Global Health Ltd.                 MEDANTA       768.65    775.45    26,139      0.00      0.00      0.00      0.00
Patanjali Foods Ltd.               PATANJALI    1313.75   1327.10    58,509      0.00      0.00      0.00      0.00
One97 Communications Ltd.          PAYTM         987.65    968.45    40,117      0.00      0.00      0.00      0.00
The Phoenix Mills Ltd.             PHOENIXLTD   1856.55   1871.80    41,150      0.00      0.00      0.00      0.00
PI Industries Ltd.                 PIIND        3467.20   3500.45    52,439      0.00      0.00      0.00      0.00

Poonawalla Fincorp Ltd.            POONAWALLA    376.70    377.65    33,895      0.00      0.00      0.00      0.00
Piramal Pharma Ltd.                PPLPHARMA      99.45     99.10    18,356      0.00      0.00      0.00      0.00
Prestige Estates Projects Ltd.     PRESTIGE      743.80    734.25    44,972      0.00      0.00      0.00      0.00
Radico Khaitan Ltd.                RADICO       1235.85   1250.85    21,588      0.00      0.00      0.00      0.00
REC Ltd.                           RECLTD        287.85    295.00   110,306      0.00      0.00      0.00      0.00

Ramkrishna Forgings Ltd.           RKFORGE       647.80    648.00    13,026      0.00      0.00      0.00      0.00
Shriram Finance Ltd.               SHRIRAMFIN   1876.70   1878.85    76,297      0.00      0.00      0.00      0.00
Solar Industries India Ltd.        SOLARINDS    5269.25   5205.25    61,544      0.00      0.00      0.00      0.00
Sonata Software Ltd.               SONATSOFTW   1111.60   1104.85    20,879      0.00      0.00      0.00      0.00
Suzlon Energy Ltd.                 SUZLON         32.50     31.60    49,718      0.00      0.00      0.00      0.00

Swan Energy Ltd.                   SWANENERGY    312.30    326.80    13,319      0.00      0.00      0.00      0.00
Tata Motors Ltd.                   TATAMOTORS    663.20    668.80   263,725      0.00      0.00      0.00      0.00
Titagarh Railsystems Ltd.          TITAGARH      844.20    795.20    14,024      0.00      0.00      0.00      0.00
Trent Ltd.                         TRENT        2036.15   2060.60   105,617      0.00      0.00      0.00      0.00
Union Bank Of India                UNIONBANK     101.15    102.50    86,874      0.00      0.00      0.00      0.00

Welspun Corp Ltd.                  WELCORP       439.45    439.65    14,270      0.00      0.00      0.00      0.00
                                   WELSPUNIND    138.10    138.55         0      0.00      0.00      0.00      0.00
Zomato Ltd.                        ZOMATO        113.35    111.65   108,929      0.00      0.00      0.00      0.00

In [276]:
print_formatted_rows(list_1k_10k, title_1k_10k)
print()
print()
print()

list_process_new(list_1k_10k, heading_1k_10k)
list_process_to_pdf(list_1k_10k, header=heading_1k_10k, output_path="heading_1k_10k.pdf")
print_formatted_rows_pdf(stock_list=list_1k_10k,title=title_1k_10k.strip(), output_path=f"{report_date}_title_1k_10k.pdf")

          Top deliveries mktcap 1k - 10k cr 231020 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Balu Forge Industries Ltd.         531112        218.60    215.25     2,575    246.74    243.97    234.44    182.80
BMW Industries Ltd.                542669         39.57     39.49     1,231     54.90     54.94     51.43     41.25
Insolation Energy Ltd.             543620        531.70    484.00     1,448    684.06    672.14    607.58    377.44
Anant Raj Ltd.                     ANANTRAJ      237.45    235.80     9,713      0.00      0.00      0.00      0.00
The Anup Engineering Ltd.          ANUP         2123.20   2157.35     2,715      0.00      0.00      0.00      0.00

Apollo Micro Systems Ltd.          APOLLO         75.35     76.85     2,987      0.00      0.00      0.00      0.00
Arvind Ltd.                        ARVIND        188.90    190.45     6,952      0.00      0.00      0.00      0.00
Arvind Fashions Ltd.               ARVINDFASN    354.15    359.80     5,563      0.00      0.00      0.00      0.00
Antony Waste Handling Cell Ltd     AWHCL         389.10    408.20     1,417      0.00      0.00      0.00      0.00
Bajaj Hindusthan Sugar Ltd.        BAJAJHIND      26.30     26.50     3,542      0.00      0.00      0.00      0.00

Banco Products (India) Ltd.        BANCOINDIA    478.65    483.05     4,642      0.00      0.00      0.00      0.00
BCL Industries Ltd.                BCLIND        521.20    521.65     1,672      0.00      0.00      0.00      0.00
Cigniti Technologies Ltd.          CIGNITITEC   1008.20    997.55     3,022      0.00      0.00      0.00      0.00
Cupid Ltd.                         CUPID         521.20    495.30     1,291      0.00      0.00      0.00      0.00
DB Realty Ltd.                     DBREALTY      158.80    163.30     9,419      0.00      0.00      0.00      0.00

Prataap Snacks Ltd.                DIAMONDYD     868.65    873.00     2,472      0.00      0.00      0.00      0.00
Dollar Industries Ltd.             DOLLAR        425.30    434.00     2,549      0.00      0.00      0.00      0.00
Electrosteel Castings Ltd.         ELECTCAST      86.00     88.35     6,811      0.00      0.00      0.00      0.00
Electronics Mart India Ltd.        EMIL          155.55    163.70     7,501      0.00      0.00      0.00      0.00
Focus Lighting & Fixtures Ltd.     FOCUS         168.80    171.40     1,187      0.00      0.00      0.00      0.00

                                   FORCEMOT     3714.45   3769.10     4,893      0.00      0.00      0.00      0.00
Gabriel India Ltd.                 GABRIEL       341.85    344.35     5,733      0.00      0.00      0.00      0.00
Gensol Engineering Ltd.            GENSOL        862.70    887.20     2,956      0.00      0.00      0.00      0.00
Genus Power Infrastructures Lt     GENUSPOWER    254.90    259.80     5,864      0.00      0.00      0.00      0.00
Hariom Pipe Industries Ltd.        HARIOMPIPE    639.55    627.80     1,756      0.00      0.00      0.00      0.00

HBL Power Systems Ltd.             HBLPOWER      288.65    295.60    12,359      0.00      0.00      0.00      0.00
Hindustan Construction Company     HCC            27.80     28.60     4,321      0.00      0.00      0.00      0.00
Hind Rectifiers Ltd.               HIRECT        364.95    370.00       943      0.00      0.00      0.00      0.00
Hi-Tech Pipes Ltd.                 HITECH         99.55    101.40     1,538      0.00      0.00      0.00      0.00
HPL Electric & Power Ltd.          HPL           208.70    210.80     1,354      0.00      0.00      0.00      0.00

Indo Count Industries Ltd.         ICIL          242.75    243.60     5,842      0.00      0.00      0.00      0.00
IFGL Refractories Ltd.             IFGLEXPOR     510.70    505.10     2,859      0.00      0.00      0.00      0.00
IIFL Securities Ltd.               IIFLSEC       100.40    105.10     4,520      0.00      0.00      0.00      0.00
IKIO Lighting Ltd.                 IKIO          349.30    349.20     2,594      0.00      0.00      0.00      0.00
Indraprastha Medical Corporati     INDRAMEDCO    164.75    167.75     1,645      0.00      0.00      0.00      0.00

Inox Wind Ltd.                     INOXWIND      212.40    214.65    15,183      0.00      0.00      0.00      0.00
JK Lakshmi Cement Ltd.             JKLAKSHMI     677.65    675.60    10,372      0.00      0.00      0.00      0.00
JK Tyre & Industries Ltd.          JKTYRE        319.70    319.90     9,290      0.00      0.00      0.00      0.00
Jaiprakash Associates Ltd.         JPASSOCIAT     12.85     13.55     5,118      0.00      0.00      0.00      0.00
Jaiprakash Power Ventures Ltd.     JPPOWER         9.70      9.95     9,519      0.00      0.00      0.00      0.00

Sai Kalamandir                     KALAMANDIR    261.60    264.15     4,219      0.00      0.00      0.00      0.00
Kesoram Industries Ltd.            KESORAMIND     82.65     84.70     5,241      0.00      0.00      0.00      0.00
KFin Technologies Ltd.             KFINTECH      461.35    453.35     8,555      0.00      0.00      0.00      0.00
KPI Green Energy Ltd.              KPIGREEN      829.30    847.90     4,999      0.00      0.00      0.00      0.00
LT Foods Ltd.                      LTFOODS       172.25    174.10     7,080      0.00      0.00      0.00      0.00

Lumax Auto Technologies Ltd.       LUMAXTECH     360.15    364.55     2,658      0.00      0.00      0.00      0.00
Man Industries (India) Ltd.        MANINDS       218.95    228.50     1,508      0.00      0.00      0.00      0.00
Marine Electricals (India) Ltd     MARINE         75.80     77.50     1,289      0.00      0.00      0.00      0.00
Marksans Pharma Ltd.               MARKSANS      106.85    108.95     7,214      0.00      0.00      0.00      0.00
MOIL Ltd.                          MOIL          247.45    261.20     6,231      0.00      0.00      0.00      0.00

Manoj Vaibhav                      MVGJL         272.50    271.45     1,635      0.00      0.00      0.00      0.00
Neuland Laboratories Ltd.          NEULANDLAB   4055.25   4160.55     6,844      0.00      0.00      0.00      0.00
Newgen Software Technologies L     NEWGEN       1129.25   1169.30    10,582      0.00      0.00      0.00      0.00
Parag Milk Foods Ltd.              PARAGMILK     216.95    223.90     2,775      0.00      0.00      0.00      0.00
Peninsula Land Ltd.                PENINLAND      40.40     36.75     1,510      0.00      0.00      0.00      0.00

PTC India Financial Services L     PFS            28.40     29.15     2,682      0.00      0.00      0.00      0.00
Pokarna Ltd.                       POKARNA       549.65    519.25     1,519      0.00      0.00      0.00      0.00
Premier Explosives Ltd.            PREMEXPLN    1238.00   1258.80     1,748      0.00      0.00      0.00      0.00
Prism Johnson Ltd.                 PRSMJOHNSN    128.00    129.75     9,179      0.00      0.00      0.00      0.00
Ramky Infrastructure Ltd.          RAMKY         632.75    627.80     5,439      0.00      0.00      0.00      0.00

RateGain Travel Technologies L     RATEGAIN      623.35    629.40     8,699      0.00      0.00      0.00      0.00
Repco Home Finance Ltd.            REPCOHOME     416.70    421.35     2,482      0.00      0.00      0.00      0.00
RPG Life Sciences Ltd.             RPGLIFE      1457.40   1425.05     2,275      0.00      0.00      0.00      0.00
Sadhana Nitro Chem Ltd.            SADHNANIQ      81.70     81.65     2,144      0.00      0.00      0.00      0.00
Sanghvi Movers Ltd.                SANGHVIMOV    701.35    690.50     3,581      0.00      0.00      0.00      0.00

Satin Creditcare Network Ltd.      SATIN         236.70    239.25     2,677      0.00      0.00      0.00      0.00
Som Distilleries Breweries & W     SDBL          315.05    316.60     2,238      0.00      0.00      0.00      0.00
Senco Gold Ltd.                    SENCO         697.30    686.85     5,612      0.00      0.00      0.00      0.00
SEPC Ltd.                          SEPC           19.15     20.10     2,946      0.00      0.00      0.00      0.00
Shriram Pistons & Rings Ltd        SHRIPISTON   1104.75   1158.80     5,908      0.00      0.00      0.00      0.00

Shriram Properties Ltd.            SHRIRAMPPS     94.70     91.25     2,052      0.00      0.00      0.00      0.00
Skipper Ltd.                       SKIPPER       227.85    232.60     2,315      0.00      0.00      0.00      0.00
Somany Ceramics Ltd.               SOMANYCERA    682.90    687.25     3,027      0.00      0.00      0.00      0.00
Spandana Sphoorty Financial Lt     SPANDANA      820.05    813.00     7,347      0.00      0.00      0.00      0.00
Transport Corporation Of India     TCI           803.60    803.05     6,352      0.00      0.00      0.00      0.00

TD Power Systems Ltd.              TDPOWERSYS    253.80    252.60     4,141      0.00      0.00      0.00      0.00
Thomas Cook (India) Ltd.           THOMASCOOK    130.35    128.75     6,576      0.00      0.00      0.00      0.00
Transformers & Rectifiers (Ind     TRIL          160.30    165.35     3,117      0.00      0.00      0.00      0.00
TV18 Broadcast Ltd.                TV18BRDCST     46.20     46.60     8,947      0.00      0.00      0.00      0.00
Vijaya Diagnostic Centre Ltd.      VIJAYA        568.00    584.80     6,458      0.00      0.00      0.00      0.00

Zaggle Prepaid                     ZAGGLE        214.75    223.15     2,709      0.00      0.00      0.00      0.00
Zee Media Corporation Ltd.         ZEEMEDIA       13.80     14.00       959      0.00      0.00      0.00      0.00



            7-day deliveries mktcap 1k - 10k cr 231020
Company Name: Balu Forge Industries Ltd. (NSE Code: 531112, BSE Code: 531112, Mktcap:2,575, Networth:430)

ema10 / ema20 / ema50 / ema200     246.74  243.97  234.44  182.8

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0          45,201          45,201     218.60
   231010               0          85,216          85,216     213.95
   230810               0         532,913         532,913     182.90
   230420               0         133,214         133,214      95.57
   190124               0              13              13      48.95

==================================================


Company Name: BMW Industries Ltd. (NSE Code: 542669, BSE Code: 542669, Mktcap:1,231, Networth:636)

ema10 / ema20 / ema50 / ema200     54.9  54.94  51.43  41.25

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0          68,820          68,820      39.57
   231010               0         313,224         313,224      41.74
   230810               0          47,518          47,518      41.88
   230420               0           4,024           4,024      33.44

==================================================


Company Name: Insolation Energy Ltd. (NSE Code: 543620, BSE Code: 543620, Mktcap:1,448, Networth:68)

ema10 / ema20 / ema50 / ema200     684.06  672.14  607.58  377.44

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0          90,000          90,000     531.70
   231010               0          95,000          95,000     439.35
   230810               0          49,000          49,000     225.25
   230420               0          27,000          27,000     138.75

==================================================


Company Name: Anant Raj Ltd. (NSE Code: ANANTRAJ, BSE Code: 515055, Mktcap:9,713, Networth:2,919)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         272,709           4,763         277,472     237.45
   231010       1,030,544          74,537       1,105,081     232.20
   230810         445,728          33,210         478,938     188.80
   230420         514,386          36,177         550,563     135.65
   190124          75,992           5,995          81,987      34.15

==================================================


Company Name: The Anup Engineering Ltd. (NSE Code: ANUP, BSE Code: 542460, Mktcap:2,715, Networth:464)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           3,387             380           3,767    2123.20
   231010          11,871             213          12,084    2050.60
   230810           9,610             611          10,221    2111.70
   230420           6,921           1,470           8,391    1105.30

==================================================


Company Name: Apollo Micro Systems Ltd. (NSE Code: APOLLO, BSE Code: 540879, Mktcap:2,987, Networth:427)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       2,212,504         196,171       2,408,675      75.35
   231010       2,245,155         522,775       2,767,930      66.70
   230810         813,336         153,898         967,234      58.00
   230420          39,887           8,309          48,196     310.25
   190124           9,251           1,300          10,551     123.25

==================================================


Company Name: Arvind Ltd. (NSE Code: ARVIND, BSE Code: 500101, Mktcap:6,952, Networth:3,362)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         197,632           8,773         206,405     188.90
   231010         284,287          13,522         297,809     176.30
   230810         332,101          18,673         350,774     141.65
   230420         357,485          29,747         387,232      96.25
   190124         209,765          37,067         246,832      89.55

==================================================


Company Name: Arvind Fashions Ltd. (NSE Code: ARVINDFASN, BSE Code: 542484, Mktcap:5,563, Networth:904)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          81,305           2,938          84,243     354.15
   231010         604,333           1,862         606,195     329.65
   230810         289,811          18,017         307,828     325.20
   230420          80,462           4,543          85,005     293.70

==================================================


Company Name: Antony Waste Handling Cell Ltd (NSE Code: AWHCL, BSE Code: 543254, Mktcap:1,417, Networth:533)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         108,622          18,494         127,116     389.10
   231010          92,275           4,331          96,606     375.55
   230810          52,426          13,771          66,197     334.65
   230420          42,806           5,708          48,514     255.90

==================================================


Company Name: Bajaj Hindusthan Sugar Ltd. (NSE Code: BAJAJHIND, BSE Code: 500032, Mktcap:3,542, Networth:4,230)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       7,214,502       1,036,781       8,251,283      26.30
   231010       4,833,225         736,823       5,570,048      25.15
   230810      24,553,191       5,028,013      29,581,204      19.85
   230420       5,339,107       1,253,558       6,592,665      14.45
   190124         474,754         105,386         580,140       8.70

==================================================


Company Name: Banco Products (India) Ltd. (NSE Code: BANCOINDIA, BSE Code: 500039, Mktcap:4,642, Networth:1,047)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          21,936           4,678          26,614     478.65
   231010          34,385           4,972          39,357     493.00
   230810         348,420          44,035         392,455     431.35
   230420          71,364          14,657          86,021     244.10
   190124          14,370             867          15,237     176.75

==================================================


Company Name: BCL Industries Ltd. (NSE Code: BCLIND, BSE Code: 524332, Mktcap:1,672, Networth:552)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          73,169             759          73,928     521.20
   231010          37,641           9,250          46,891     534.15
   230810          19,440             851          20,291     471.50
   230420          14,371           4,258          18,629     440.35
   190124               0           3,231           3,231     102.70

==================================================


No data found for BLUEJET

Company Name: Cigniti Technologies Ltd. (NSE Code: CIGNITITEC, BSE Code: 534758, Mktcap:3,022, Networth:668)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         147,576           9,430         157,006    1008.20
   231010          65,709           4,896          70,605     823.25
   230810          63,635           5,380          69,015     764.15
   230420          33,509           4,192          37,701     802.40
   190124          16,536             305          16,841     363.10

==================================================


Company Name: Cupid Ltd. (NSE Code: CUPID, BSE Code: 530843, Mktcap:1,291, Networth:171)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         489,576          21,794         511,370     521.20
   231010          38,262           5,139          43,401     404.95
   230810          98,421          11,671         110,092     291.35
   230420          15,998           4,556          20,554     269.40
   190124          20,332           1,511          21,843     130.50

==================================================


Company Name: DB Realty Ltd. (NSE Code: DBREALTY, BSE Code: 533160, Mktcap:9,419, Networth:3,732)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         524,033          44,449         568,482     158.80
   231010       1,192,451         103,750       1,296,201     170.25
   230810         823,921          78,430         902,351      98.65
   230420         132,556          29,035         161,591      88.80
   190124          87,380          16,870         104,250      27.05

==================================================


Company Name: Prataap Snacks Ltd. (NSE Code: DIAMONDYD, BSE Code: 540724, Mktcap:2,472, Networth:676)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           3,222              25           3,247     868.65
   231010           3,141             243           3,384     846.85
   230810           5,050             487           5,537     906.55
   230420           3,046             154           3,200     698.10
   190124           1,833              15           1,848    1030.25

==================================================


Company Name: Dollar Industries Ltd. (NSE Code: DOLLAR, BSE Code: 541403, Mktcap:2,549, Networth:741)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          38,430           2,981          41,411     425.30
   231010          52,267           2,353          54,620     434.25
   230810         119,305           5,545         124,850     446.10
   230420         267,456          14,338         281,794     364.05
   190124           2,340             831           3,171     287.65


In [277]:
print_formatted_rows(list_below_1000, title_below_1000)
print()
print()
print()
list_process_new(list_below_1000, heading_below_1000)
list_process_to_pdf(list_below_1000, header=heading_below_1000, output_path="heading_below_1000.pdf")
print_formatted_rows_pdf(stock_list=list_below_1000,title=title_below_1000.strip(), output_path=f"{report_date}_title_below_1000.pdf")

         Top deliveries mktcap below 1000 cr 231020 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


20 Microns Ltd.                    20MICRONS     134.95    137.70       667      0.00      0.00      0.00      0.00
Kilburn Engineering Ltd.           522101        205.80    197.00     1,067    282.14    278.92    255.32    179.65
Nile Ltd.                          530129        710.95    714.15       262    878.40    881.02    844.51    735.64
Ceinsys Tech Ltd.                  538734        261.30    268.10       542    356.46    356.08    336.10    251.65
RMC Switchgears Ltd.               540358        644.95    592.05       608    584.15    586.85    603.08    515.17

Khazanchi Jewellers Ltd            543953        229.00    228.50       678    274.50    276.12    264.36    207.34
Bondada Engineering Limited        543971        269.40    259.60       817    395.87    397.40    359.02    242.00
Annapurna Swadisht Ltd.            ANNAPURNA     306.90    307.60       556    331.49    334.41    326.04    278.64
Arihant Superstructures Ltd.       ARIHANTSUP    186.10    190.05     1,118      0.00      0.00      0.00      0.00
Chembond Chemicals Ltd.            CHEMBOND      371.45    372.60       733      0.00      0.00      0.00      0.00

Dharmaj Crop Guard Ltd.            DHARMAJ       255.00    252.35       900      0.00      0.00      0.00      0.00
Global Education Ltd.              GLOBAL        194.35    196.95       633      0.00      0.00      0.00      0.00
Indo Tech Transformers Ltd.        INDOTECH      505.85    516.15       668      0.00      0.00      0.00      0.00
Kapston Services Ltd.              KAPSTON       180.55    179.25       250      0.00      0.00      0.00      0.00
Kothari Petrochemicals Ltd.        KOTHARIPET    136.60    140.65       897      0.00      0.00      0.00      0.00

Magson Retail & Distribution L     MAGSON         88.30     87.10       106    129.73    125.84    115.22     95.25
MBL Infrastructure Ltd.            MBLINFRA       30.50     29.05       477      0.00      0.00      0.00      0.00
Modison Ltd.                       MODISONLTD     79.85     81.70       423      0.00      0.00      0.00      0.00
NDR Auto Components Ltd.           NDRAUTO       594.10    606.20       925      0.00      0.00      0.00      0.00
Pyramid Technoplast Limited        PYRAMID       221.95    228.00       722      0.00      0.00      0.00      0.00

Semac Consultants Ltd              SEMAC        2371.00   2371.50       708      0.00      0.00      0.00      0.00
Sky Gold Ltd.                      SKYGOLD       753.05    738.40     1,079      0.00      0.00      0.00      0.00
Venus Remedies Ltd.                VENUSREM      254.45    257.45       527      0.00      0.00      0.00      0.00
Walchandnagar Industries Ltd.      WALCHANNAG    168.30    171.70       905      0.00      0.00      0.00      0.00



          7-day deliveries mktcap below 1000 cr 231020
Company Name: 20 Microns Ltd. (NSE Code: 20MICRONS, BSE Code: 533022, Mktcap:667, Networth:322)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          11,997           4,454          16,451     134.95
   231010           5,084           1,158           6,242     151.45
   230810          14,575          15,659          30,234     114.55
   230420          44,083           2,964          47,047      83.80
   190124           8,809           1,696          10,505      39.75

==================================================


Company Name: Kilburn Engineering Ltd. (NSE Code: 522101, BSE Code: 522101, Mktcap:1,067, Networth:136)

ema10 / ema20 / ema50 / ema200     282.14  278.92  255.32  179.65

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0         123,287         123,287     205.80
   231010               0         151,436         151,436     202.20
   230810               0          33,681          33,681     165.90
   230420               0          75,416          75,416      96.93
   190124               0               1               1      51.35

==================================================


Company Name: Nile Ltd. (NSE Code: 530129, BSE Code: 530129, Mktcap:262, Networth:213)

ema10 / ema20 / ema50 / ema200     878.4  881.02  844.51  735.64

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0             886             886     710.95
   231010               0           1,311           1,311     691.20
   230810               0           1,852           1,852     727.20
   230420               0           1,011           1,011     553.40
   190124               0           3,216           3,216     348.30

==================================================


Company Name: Ceinsys Tech Ltd. (NSE Code: 538734, BSE Code: 538734, Mktcap:542, Networth:211)

ema10 / ema20 / ema50 / ema200     356.46  356.08  336.1  251.65

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0          71,262          71,262     261.30
   231010               0          60,515          60,515     278.60
   230810               0          33,345          33,345     198.15
   230420               0             264             264     156.50
   190124               0           3,007           3,007     101.00

==================================================


Company Name: RMC Switchgears Ltd. (NSE Code: 540358, BSE Code: 540358, Mktcap:608, Networth:54)

ema10 / ema20 / ema50 / ema200     584.15  586.85  603.08  515.17

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0          19,500          19,500     644.95
   231010               0          17,000          17,000     759.00
   230810               0          17,500          17,500     590.75
   230420               0           4,000           4,000     283.50

==================================================


Company Name: Khazanchi Jewellers Ltd (NSE Code: 543953, BSE Code: 543953, Mktcap:678, Networth:161)

ema10 / ema20 / ema50 / ema200     274.5  276.12  264.36  207.34

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0           6,000           6,000     229.00
   231010               0          29,000          29,000     208.95
   230810               0         139,000         139,000     144.10

==================================================


Company Name: Bondada Engineering Limited (NSE Code: 543971, BSE Code: 543971, Mktcap:817, Networth:130)

ema10 / ema20 / ema50 / ema200     395.87  397.4  359.02  242.0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020               0         238,400         238,400     269.40
   231010               0         603,200         603,200     209.75

==================================================


Company Name: Annapurna Swadisht Ltd. (NSE Code: ANNAPURNA, BSE Code: 0, Mktcap:556, Networth:93)

ema10 / ema20 / ema50 / ema200     331.49  334.41  326.04  278.64

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          68,000               0          68,000     306.90
   231010          90,000               0          90,000     289.90
   230810          20,000               0          20,000     308.00
   230420         135,000               0         135,000     236.55

==================================================


Company Name: Arihant Superstructures Ltd. (NSE Code: ARIHANTSUP, BSE Code: 506194, Mktcap:1,118, Networth:234)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          34,165          12,928          47,093     186.10
   231010          47,935           5,220          53,155     185.10
   230810          24,452          15,319          39,771     168.10
   230420          49,294          40,009          89,303     215.05
   190124          12,478           3,947          16,425      52.00

==================================================


Company Name: Chembond Chemicals Ltd. (NSE Code: CHEMBOND, BSE Code: 530871, Mktcap:733, Networth:343)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           2,661             336           2,997     371.45
   231010          10,387           2,545          12,932     378.10
   230810          31,060           2,945          34,005     424.35
   230420           4,835           1,409           6,244     276.50
   190124               0             520             520     341.30

==================================================


Company Name: Dharmaj Crop Guard Ltd. (NSE Code: DHARMAJ, BSE Code: 543687, Mktcap:900, Networth:359)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         149,966          19,226         169,192     255.00
   231010         165,087          25,760         190,847     237.35
   230810         200,885          11,843         212,728     219.05
   230420          14,290           5,596          19,886     167.00

==================================================


Company Name: Global Education Ltd. (NSE Code: GLOBAL, BSE Code: 0, Mktcap:633, Networth:78)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          10,770               0          10,770     194.35
   231010          21,677               0          21,677     189.00
   230810          40,959               0          40,959     185.85
   230420          54,330               0          54,330     145.50
   190124           1,000               0           1,000     149.00

==================================================


Company Name: Indo Tech Transformers Ltd. (NSE Code: INDOTECH, BSE Code: 532717, Mktcap:668, Networth:181)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020             746              20             766     505.85
   231010          22,988           4,539          27,527     483.95
   230810          12,142           7,192          19,334     482.65
   230420           6,383           3,558           9,941     199.15
   190124           3,601             416           4,017     111.10

==================================================


Company Name: Kapston Services Ltd. (NSE Code: KAPSTON, BSE Code: 0, Mktcap:250, Networth:66)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           3,937               0           3,937     180.55
   231010           8,215               0           8,215     172.90
   230810           3,779               0           3,779     159.55
   230420           2,147               0           2,147     138.40

==================================================


Company Name: Kothari Petrochemicals Ltd. (NSE Code: KOTHARIPET, BSE Code: 532096, Mktcap:897, Networth:222)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          74,731               0          74,731     136.60
   231010         991,368               0         991,368     137.25
   230810         315,003               0         315,003     111.20
   230420          15,438               0          15,438      63.70
   190124             852               0             852      20.70

==================================================


Company Name: Magson Retail & Distribution L (NSE Code: MAGSON, BSE Code: 0, Mktcap:106, Networth:21)

ema10 / ema20 / ema50 / ema200     129.73  125.84  115.22  95.25

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          14,000               0          14,000      88.30
   231010          52,000               0          52,000      87.05
   230810          18,000               0          18,000      81.00

==================================================


Company Name: MBL Infrastructure Ltd. (NSE Code: MBLINFRA, BSE Code: 533152, Mktcap:477, Networth:767)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         147,297         102,528         249,825      30.50
   231010          66,340          28,739          95,079      27.05
   230810         103,203         114,808         218,011      24.00
   230420          21,048           1,118          22,166      18.05
   190124          96,698          13,878         110,576      14.85

==================================================


Company Name: Modison Ltd. (NSE Code: MODISONLTD, BSE Code: 506261, Mktcap:423, Networth:195)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          14,901           2,975          17,876      79.85
   231010          35,024           5,161          40,185      78.35
   230810          85,337          15,687         101,024      78.00
   230420          11,063           2,848          13,911      61.60
   190124               0           2,500           2,500      43.25

==================================================


Company Name: NDR Auto Components Ltd. (NSE Code: NDRAUTO, BSE Code: 543214, Mktcap:925, Networth:234)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           1,416             679           2,095     594.10
   231010           1,439             889           2,328     615.05
   230810           1,713           1,742           3,455     454.55
   230420           8,075             771           8,846     590.80

==================================================


Company Name: Pyramid Technoplast Limited (NSE Code: PYRAMID, BSE Code: 543969, Mktcap:722, Networth:208)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         392,602         101,291         493,893     221.95
   231010         768,775         100,245         869,020     184.70

==================================================


Company Name: Semac Consultants Ltd (NSE Code: SEMAC, BSE Code: 505368, Mktcap:708, Networth:110)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020             157             909           1,066    2371.00
   231010             802              75             877    2307.00
   230810               0              80              80    1495.75
   230420               0             367             367    1274.90

==================================================


Company Name: Sky Gold Ltd. (NSE Code: SKYGOLD, BSE Code: 541967, Mktcap:1,079, Networth:114)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         193,837          41,900         235,737     753.05
   231010         521,573          44,706         566,279     392.55
   230810          14,903             243          15,146     254.60
   230420          18,848           1,664          20,512     342.75
   190124               0          38,400          38,400     182.00

==================================================


Company Name: Venus Remedies Ltd. (NSE Code: VENUSREM, BSE Code: 526953, Mktcap:527, Networth:471)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          12,195           3,204          15,399     254.45
   231010          12,860           4,707          17,567     226.05
   230810          22,823          10,515          33,338     266.70
   230420          37,326           5,392          42,718     205.70
   190124           4,229           1,082           5,311      40.45

==================================================


Company Name: Walchandnagar Industries Ltd. (NSE Code: WALCHANNAG, BSE Code: 507410, Mktcap:905, Networth:243)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         248,222          58,839         307,061     168.30
   231010          55,869           6,558          62,427     138.50
   230810         115,343          51,556         166,899     115.55
   230420          33,142           4,507          37,649      64.20
   190124          52,016           9,203          61,219      96.75

==================================================

In [26]:
print("                         Top Deliveries with averages ", report_date)
print('________________________________________________________________________________________________________________')
print("")
print("")
print("")

print_formatted_rows(unique_non_fno,title_non_fno)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(sme_list,title_sme)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_above_10k,title_above_10k)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_1k_10k,title_1k_10k)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_below_1000, title_below_1000)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

                         Top Deliveries with averages  231226
________________________________________________________________________________________________________________



Non_fno top deliveries 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Indian Renewable Energy Dev Ag     IREDA         101.95    109.85    27,399      0.00      0.00      0.00      0.00
Mazagon Dock Shipbuilders Ltd.     MAZDOCK      2287.85   2121.40    46,195      0.00      0.00      0.00      0.00
Castrol India Ltd.                 CASTROLIND    182.55    162.55    18,017      0.00      0.00      0.00      0.00
Adani Green Energy Ltd.            ADANIGREEN   1600.20   1533.10   253,289      0.00      0.00      0.00      0.00
Indian Railway Finance Corpora     IRFC           97.40     97.75   127,287      0.00      0.00      0.00      0.00

Cochin Shipyard Ltd.               COCHINSHIP   1374.50   1301.40    18,061      0.00      0.00      0.00      0.00
JIO Financial Services             JIOFIN        234.70    236.75   149,048      0.00      0.00      0.00      0.00
Mahindra Lifespace Developers      MAHLIFE       540.40    532.35     8,370      0.00      0.00      0.00      0.00
HFCL Ltd.                          HFCL           85.80     82.00    12,260      0.00      0.00      0.00      0.00
                                   LIQUIDBEES    999.99   1000.00         0      0.00      0.00      0.00      0.00

Zomato Ltd.                        ZOMATO        125.00    128.50   108,929      0.00      0.00      0.00      0.00
Adani Energy Solutions             ADANIENSOL   1041.60   1027.90   116,111      0.00      0.00      0.00      0.00
IIFL Finance Ltd.                  IIFL          592.40    572.60    22,559      0.00      0.00      0.00      0.00
Muthoot Microfin Limited           MUTHOOTMF     266.15    291.00         0      0.00      0.00      0.00      0.00
Motisons Jewellers Limited         MOTISONS      103.55     55.00         0      0.00      0.00      0.00      0.00

Varun Beverages Ltd.               VBL          1250.05   1238.60   162,202      0.00      0.00      0.00      0.00
Inox India Limited                 INOXINDIA     928.85    910.65     8,435      0.00      0.00      0.00      0.00
Bharat Dynamics Ltd.               BDL          1694.80   1571.25    31,014      0.00      0.00      0.00      0.00
Ircon International Ltd.           IRCON         171.20    166.60    16,106      0.00      0.00      0.00      0.00
Arman Financial Services Ltd.      ARMANFIN     2508.85   2609.70     2,197      0.00      0.00      0.00      0.00

One97 Communications Ltd.          PAYTM         631.80    642.20    40,117      0.00      0.00      0.00      0.00
Oil India Ltd.                     OIL           381.70    373.25    41,408      0.00      0.00      0.00      0.00
Star Health and Allied Insuran     STARHEALTH    533.80    522.40    31,262      0.00      0.00      0.00      0.00
Yes Bank Ltd.                      YESBANK        20.95     21.05    60,284      0.00      0.00      0.00      0.00
NLC India Ltd.                     NLCINDIA      250.20    223.90    34,741      0.00      0.00      0.00      0.00

Suzlon Energy Ltd.                 SUZLON         36.90     37.25    49,718      0.00      0.00      0.00      0.00
Jupiter Wagons Ltd.                JWL           320.30    323.70    13,202      0.00      0.00      0.00      0.00
Garden Reach Shipbuilders & En     GRSE          872.20    819.65     9,991      0.00      0.00      0.00      0.00
                                   SETFNIF50     223.54    222.74         0      0.00      0.00      0.00      0.00
Solara Active Pharma Sciences      SOLARA        375.95    329.05     1,349      0.00      0.00      0.00      0.00

Himadri Speciality Chemical Lt     HSCL          307.35    286.55    13,561      0.00      0.00      0.00      0.00
Avenue Supermarts Ltd.             DMART        4023.45   4007.95   261,382      0.00      0.00      0.00      0.00
Bank Of India                      BANKINDIA     109.50    111.80    49,807      0.00      0.00      0.00      0.00
BSE Ltd.                           BSE          2310.60   2319.90    31,280      0.00      0.00      0.00      0.00
MSTC Ltd.                          MSTCLTD       643.45    568.00     4,537      0.00      0.00      0.00      0.00

Shyam Metalics And Energy Ltd.     SHYAMMETL     619.10    608.40    15,775      0.00      0.00      0.00      0.00
Suraj Estate Developers Limite     SURAJEST      334.50    360.00         0      0.00      0.00      0.00      0.00
MTAR Technologies Ltd.             MTARTECH     2174.60   2236.65     6,688      0.00      0.00      0.00      0.00
J Kumar Infraprojects Ltd.         JKIL          593.50    494.60     4,491      0.00      0.00      0.00      0.00
Balaji Amines Ltd.                 BALAMINES    2614.60   2365.20     8,461      0.00      0.00      0.00      0.00

Jaiprakash Power Ventures Ltd.     JPPOWER        13.95     13.25     9,519      0.00      0.00      0.00      0.00
Indian Bank                        INDIANB       409.70    412.20    55,118      0.00      0.00      0.00      0.00
Adani Total Gas Ltd.               ATGL          995.05    996.30   109,026      0.00      0.00      0.00      0.00
India Pesticides Ltd.              IPL           369.60    354.55     4,273      0.00      0.00      0.00      0.00
Life Insurance Corporation of      LICI          781.30    792.80   494,048      0.00      0.00      0.00      0.00

JSW Energy Ltd.                    JSWENERGY     415.15    409.30    68,278      0.00      0.00      0.00      0.00
Balmer Lawrie & Company Ltd.       BALMLAWRIE    230.25    224.90     3,941      0.00      0.00      0.00      0.00
Swan Energy Ltd.                   SWANENERGY    503.35    506.40    13,319      0.00      0.00      0.00      0.00
Alkyl Amines Chemicals Ltd.        ALKYLAMINE   2570.90   2304.85    13,124      0.00      0.00      0.00      0.00
Rail Vikas Nigam Ltd.              RVNL          178.65    176.90    37,239      0.00      0.00      0.00      0.00

Syncom Formulations (India) Lt     SYNCOMF        14.15     11.80     1,330      0.00      0.00      0.00      0.00
Akshar Spintex Ltd.                AKSHAR          5.10      5.65       127      0.00      0.00      0.00      0.00
RattanIndia Power Ltd.             RTNPOWER        9.25      9.15     4,967      0.00      0.00      0.00      0.00
Reliance Power Ltd.                RPOWER         22.60     22.40     8,602      0.00      0.00      0.00      0.00
Urja Global Ltd.                   URJA           15.25     14.00       802      0.00      0.00      0.00      0.00

The South Indian Bank Ltd.         SOUTHBANK      26.10     26.65     5,462      0.00      0.00      0.00      0.00
Jaiprakash Associates Ltd.         JPASSOCIAT     20.85     21.10     5,118      0.00      0.00      0.00      0.00
Rajnandini Metal Ltd.              RAJMET         10.55      9.65       292      0.00      0.00      0.00      0.00
PC Jeweller Ltd.                   PCJEWELLER     46.50     51.65     2,164      0.00      0.00      0.00      0.00
Infibeam Avenues Ltd.              INFIBEAM       21.95     21.70     6,096      0.00      0.00      0.00      0.00

Subex Ltd.                         SUBEXLTD       36.70     35.50     2,069      0.00      0.00      0.00      0.00
Hindustan Construction Company     HCC            28.60     29.05     4,321      0.00      0.00      0.00      0.00
TV18 Broadcast Ltd.                TV18BRDCST     52.15     51.00     8,947      0.00      0.00      0.00      0.00
Morepen Laboratories Ltd.          MOREPENLAB     51.85     49.25     2,642      0.00      0.00      0.00      0.00
Dish TV India Ltd.                 DISHTV         19.35     19.75     3,574      0.00      0.00      0.00      0.00

Mishtann Foods Ltd.                539594         17.14     16.44     1,714     16.59     16.25     15.21     12.57
Easy Trip Planners Ltd.            EASEMYTRIP     39.05     38.50     6,785      0.00      0.00      0.00      0.00
NHPC Ltd.                          NHPC           64.60     64.70    64,881      0.00      0.00      0.00      0.00
Brightcom Group Ltd.               BCG            19.35     19.85     3,909      0.00      0.00      0.00      0.00
Hathway Cable & Datacom Ltd.       HATHWAY        22.10     22.05     3,915      0.00      0.00      0.00      0.00

DCW Ltd.                           DCW            57.80     54.85     1,707      0.00      0.00      0.00      0.00

SJVN Ltd.                          SJVN           91.55     89.70    36,029      0.00      0.00      0.00      0.00
Network 18 Media & Investments     NETWORK18      88.85     86.10     9,285      0.00      0.00      0.00      0.00
IRB Infrastructure Developers      IRB            41.85     41.65    25,249      0.00      0.00      0.00      0.00
Orient Green Power Company Ltd     GREENPOWER     21.95     22.35     2,154      0.00      0.00      0.00      0.00

National Fertilizers Ltd.          NFL            85.90     84.25     4,213      0.00      0.00      0.00      0.00
Ultracab (India) Ltd.              538706         27.83     24.30       266     24.50     23.17     20.75     18.94
IFCI Ltd.                          IFCI           28.15     28.40     7,003      0.00      0.00      0.00      0.00
CESC Ltd.                          CESC          123.40    119.15    16,357      0.00      0.00      0.00      0.00
Trident Ltd.                       TRIDENT        36.05     36.15    18,371      0.00      0.00      0.00      0.00

VL E-Governance & IT Solutions     VLEGOV         41.60     34.70       441      0.00      0.00      0.00      0.00
Bajaj Hindusthan Sugar Ltd.        BAJAJHIND      27.75     27.90     3,542      0.00      0.00      0.00      0.00
Union Bank Of India                UNIONBANK     117.15    118.25    86,874      0.00      0.00      0.00      0.00
Himachal Fibres Ltd.               514010         29.67     30.27       256     30.21     28.53     23.47     13.35
Bank Of Maharashtra                MAHABANK       45.25     45.60    32,036      0.00      0.00      0.00      0.00

________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

SME top deliveries 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Droneacharya Aerial Innovation     543713        175.20    185.75       420    191.32    190.91    186.08    165.06
Kalyani Cast Tech Limited          544023        446.75    406.15       321    406.53    392.49    352.79    302.71
VishnuSurya Infra                  VISHNUINFR    445.50    428.40     1,096      0.00      0.00      0.00      0.00
Amic Forging Limited               544037        395.90    353.05       415    344.40    317.71    285.61    261.21
Insolation Energy Ltd.             543620        685.00    696.20     1,448    684.06    672.14    607.58    377.44

Basilic Fly Studio                 BASILIC       302.05    301.95       702    294.99    294.44    291.89    288.10
All E Technologies Ltd.            ALLETEC       235.50    256.75       476    249.41    248.40    232.00    170.97
Varanium Cloud Ltd.                CLOUD         100.90    101.95       406    105.37    110.49    123.88    151.01
Gretex Corporate Services Ltd.     543324        328.95    303.50       380    274.85    250.12    230.63    194.69
Presstonic Engineering Limited     PRESSTONIC    137.20    131.65       106      0.00      0.00      0.00      0.00

Waaree Technologies Ltd.           539337        730.30    695.60       786    629.05    571.54    502.72    384.66
S J Logistics                      SJLOGISTIC    168.40    174.10       244      0.00      0.00      0.00      0.00
Phantom Digital Effects Ltd.       PHANTOMFX     491.80    520.30       572    462.86    446.12    437.81    395.67
Cellcor Gadgets                    CELLECOR      289.20    264.20       606    260.08    250.06    227.49    184.22
Indo US Bio-Tech Ltd.              541304        243.10    239.00       491    234.55    223.85    211.51    158.62

Sheetal Universal Limited          SHEETAL        86.10     75.20        99     72.42     73.21     74.27     75.08
HiGreen Carbon                     HIGREEN       180.15    180.80       450    181.45    176.55    164.12    147.34
Kody Techno                        KODYTECH      513.60    428.45       327    404.92    373.19    334.40    284.13
Network People Services Techno     NPST         2316.45   2206.15     1,497   2205.91   2134.80   1655.81    689.18
Concord Control Systems Ltd.       543619        796.80    664.00       477    699.56    690.52    654.54    467.61

Remus Pharmaceuticals Ltd.         REMUS        7587.25   7060.00     1,118   6497.76   6099.95   5628.39   4360.30
Rocking Deals Circular Economy     ROCKINGDCE    312.65    331.90       177      0.00      0.00      0.00      0.00
Benchmark Computer Solutions L     544052         76.93     73.27        53     76.51     76.77     76.97     77.08
RMC Switchgears Ltd.               540358        587.75    578.75       608    584.15    586.85    603.08    515.17
ROX Hitech Limited                 ROXHITECH     165.70    159.15       378    165.07    157.77    149.68    143.97

Graphisads Limited                 GRAPHISAD      76.80     80.80       140     89.33     95.31    100.92    104.57
Chavda Infra                       CHAVDA         86.55     80.10       213     85.21     87.60     89.98     89.21
Supershakti Metaliks Ltd.          541701        460.00    460.00       530    469.52    469.63    442.84    367.48
Accent Microcell Limited           ACCENTMIC     279.45    288.55       588    292.66    300.83    308.38    313.21
Sahara Maritime Limited            544056         81.16      0.00         0     81.16     81.16     81.16     81.16

Taylormade Renewables Ltd.         541228        766.35    729.90       842    720.73    714.72    664.48    474.42
Vinyas Innovative Technologies     VINYAS        751.65    735.55       946    609.65    550.22    499.33    470.00
Bondada Engineering Limited        543971        379.75    391.75       817    395.87    397.40    359.02    242.00
Oriana Power Limited               ORIANA        496.60    501.80       953    485.79    453.83    404.22    380.93
Cosmic CRF Ltd.                    543928        446.85    413.70       312    400.68    374.89    331.56    276.80

SAR Televenture Ltd                SARTELE       164.85    171.35       247    101.68    104.07    107.05    109.33
Essen Speciality Films Ltd.        ESFL          210.60    214.10       436    218.33    213.12    192.86    159.23
Jayant Infratech Ltd.              543544        197.30    190.10       194    180.18    163.94    134.67    105.31
Paragon Fine and Speciality Ch     PARAGON       137.10    145.00       268    199.57    203.10    208.10    212.11
Crop Life Science Limited          CLSL           47.55     42.40        82     42.16     41.39     41.33     43.30

Sahana System Ltd.                 SAHANA        647.95    617.10       518    594.64    577.04    501.24    308.95
Arihant Academy Ltd.               ARIHANTACA    171.70    173.55       104      0.00      0.00      0.00      0.00
Baba Food Processing Private L     BABAFP         69.45     65.30       113     73.30     72.70     72.36     72.23
Dev Labtech Venture Ltd.           543848         84.75     88.47        70     80.42     78.66     74.83     64.52
Transteel Seating Technologies     TRANSTEEL      80.95     83.80       163     98.62     97.76     95.80     94.04

Viaz Tyres Ltd.                    VIAZ           66.80     58.05        82     56.38     51.94     47.73     49.40
Rachana Infrastructure Ltd.        RILINFRA       86.20     88.00       160     88.97     90.90     95.95    186.86
Kundan Edifice                     KEL           239.70    252.30       246    228.72    199.85    151.05     99.97
Kotyark Industries Ltd.            KOTYARK       947.80    954.90       828    942.45    909.44    838.68    653.65
Synoptics Technologies Ltd.        SYNOPTICS     134.10    128.00       114    130.05    129.57    130.71    144.91

________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

         Top deliveries mktcap above 10k cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Adani Power Ltd.                   ADANIPOWER    511.70    512.55   197,823      0.00      0.00      0.00      0.00
Amber Enterprises India Ltd.       AMBER        3041.15   3051.55    10,245      0.00      0.00      0.00      0.00
Angel One Ltd.                     ANGELONE     3288.20   3292.35    27,611      0.00      0.00      0.00      0.00
Bikaji Foods International Ltd     BIKAJI        553.30    552.35    13,823      0.00      0.00      0.00      0.00
Blue Star Ltd.                     BLUESTARCO    946.95    951.25    19,465      0.00      0.00      0.00      0.00

Brigade Enterprises Ltd.           BRIGADE       859.50    868.80    19,992      0.00      0.00      0.00      0.00
BSE Ltd.                           BSE          2310.60   2319.90    31,280      0.00      0.00      0.00      0.00

Central Depository Services (I     CDSL         1851.05   1836.95    19,343      0.00      0.00      0.00      0.00
Cello World Limited                CELLO         765.50    769.20    16,257      0.00      0.00      0.00      0.00
Concord Biotech                    CONCORDBIO   1506.10   1504.70    15,715      0.00      0.00      0.00      0.00

CreditAccess Grameen Ltd.          CREDITACC    1613.25   1627.50    25,711      0.00      0.00      0.00      0.00
Elecon Engineering Company Ltd     ELECON        940.25    893.50    10,549      0.00      0.00      0.00      0.00
Vodafone Idea Ltd.                 IDEA           13.35     13.60    65,037      0.00      0.00      0.00      0.00
Jindal Saw Ltd.                    JINDALSAW     422.15    424.40    13,481      0.00      0.00      0.00      0.00
JK Cement Ltd.                     JKCEMENT     3765.40   3782.20    29,238      0.00      0.00      0.00      0.00

Jupiter Wagons Ltd.                JWL           320.30    323.70    13,202      0.00      0.00      0.00      0.00
KPIT Technologies Ltd.             KPITTECH     1527.70   1539.35    41,870      0.00      0.00      0.00      0.00
L&T Finance Holdings Ltd.          L&TFH         153.00    152.80    38,048      0.00      0.00      0.00      0.00
Dr. Lal Pathlabs Ltd.              LALPATHLAB   2600.05   2596.50    21,721      0.00      0.00      0.00      0.00
Macrotech Developers Ltd.          LODHA         952.80    937.20    91,717      0.00      0.00      0.00      0.00

Multi Commodity Exchange Of In     MCX          3144.15   3163.85    16,043      0.00      0.00      0.00      0.00
Global Health Ltd.                 MEDANTA       963.65    973.85    26,139      0.00      0.00      0.00      0.00
Patanjali Foods Ltd.               PATANJALI    1617.90   1621.65    58,509      0.00      0.00      0.00      0.00
One97 Communications Ltd.          PAYTM         631.80    642.20    40,117      0.00      0.00      0.00      0.00
The Phoenix Mills Ltd.             PHOENIXLTD   2304.85   2298.50    41,150      0.00      0.00      0.00      0.00

PI Industries Ltd.                 PIIND        3451.85   3427.95    52,439      0.00      0.00      0.00      0.00
Poonawalla Fincorp Ltd.            POONAWALLA    440.25    442.35    33,895      0.00      0.00      0.00      0.00
Piramal Pharma Ltd.                PPLPHARMA     138.60    140.50    18,356      0.00      0.00      0.00      0.00
Prestige Estates Projects Ltd.     PRESTIGE     1121.30   1114.90    44,972      0.00      0.00      0.00      0.00
Radico Khaitan Ltd.                RADICO       1615.15   1602.50    21,588      0.00      0.00      0.00      0.00

REC Ltd.                           RECLTD        419.00    406.60   110,306      0.00      0.00      0.00      0.00
Ramkrishna Forgings Ltd.           RKFORGE       724.65    724.40    13,026      0.00      0.00      0.00      0.00
Shriram Finance Ltd.               SHRIRAMFIN   2035.75   2055.45    76,297      0.00      0.00      0.00      0.00
Solar Industries India Ltd.        SOLARINDS    6793.15   6594.90    61,544      0.00      0.00      0.00      0.00
Sonata Software Ltd.               SONATSOFTW    744.55    749.90    20,879      0.00      0.00      0.00      0.00

Suzlon Energy Ltd.                 SUZLON         36.90     37.25    49,718      0.00      0.00      0.00      0.00
Swan Energy Ltd.                   SWANENERGY    503.35    506.40    13,319      0.00      0.00      0.00      0.00
Tata Motors Ltd.                   TATAMOTORS    719.55    724.70   263,725      0.00      0.00      0.00      0.00
Titagarh Railsystems Ltd.          TITAGARH     1038.90   1047.85    14,024      0.00      0.00      0.00      0.00
Trent Ltd.                         TRENT        2970.00   2965.50   105,617      0.00      0.00      0.00      0.00

Union Bank Of India                UNIONBANK     117.15    118.25    86,874      0.00      0.00      0.00      0.00
Welspun Corp Ltd.                  WELCORP       545.10    530.55    14,270      0.00      0.00      0.00      0.00
Zomato Ltd.                        ZOMATO        125.00    128.50   108,929      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

          Top deliveries mktcap 1k - 10k cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Balu Forge Industries Ltd.         531112        250.95    248.20     2,575    246.74    243.97    234.44    182.80
BMW Industries Ltd.                542669         54.67     52.45     1,231     54.90     54.94     51.43     41.25
Insolation Energy Ltd.             543620        685.00    696.20     1,448    684.06    672.14    607.58    377.44
Anant Raj Ltd.                     ANANTRAJ      299.05    303.15     9,713      0.00      0.00      0.00      0.00
The Anup Engineering Ltd.          ANUP         2732.00   2638.00     2,715      0.00      0.00      0.00      0.00

Apollo Micro Systems Ltd.          APOLLO        114.05    114.70     2,987      0.00      0.00      0.00      0.00
Arvind Ltd.                        ARVIND        266.35    259.30     6,952      0.00      0.00      0.00      0.00
Arvind Fashions Ltd.               ARVINDFASN    419.20    412.15     5,563      0.00      0.00      0.00      0.00
Antony Waste Handling Cell Ltd     AWHCL         501.50    488.80     1,417      0.00      0.00      0.00      0.00
Bajaj Hindusthan Sugar Ltd.        BAJAJHIND      27.75     27.90     3,542      0.00      0.00      0.00      0.00

Banco Products (India) Ltd.        BANCOINDIA    651.05    618.75     4,642      0.00      0.00      0.00      0.00
BCL Industries Ltd.                BCLIND         65.95     66.50     1,672      0.00      0.00      0.00      0.00
Blue Jet Healthcare Limited        BLUEJET       369.65    361.30     6,439      0.00      0.00      0.00      0.00
Cigniti Technologies Ltd.          CIGNITITEC   1108.65   1125.75     3,022      0.00      0.00      0.00      0.00
Cupid Ltd.                         CUPID         967.90    921.85     1,291      0.00      0.00      0.00      0.00

DB Realty Ltd.                     DBREALTY      187.55    191.85     9,419      0.00      0.00      0.00      0.00
Prataap Snacks Ltd.                DIAMONDYD    1024.40    965.55     2,472      0.00      0.00      0.00      0.00
Dollar Industries Ltd.             DOLLAR        449.70    440.10     2,549      0.00      0.00      0.00      0.00
Electrosteel Castings Ltd.         ELECTCAST     114.45    112.90     6,811      0.00      0.00      0.00      0.00
Electronics Mart India Ltd.        EMIL          203.30    205.70     7,501      0.00      0.00      0.00      0.00

Focus Lighting & Fixtures Ltd.     FOCUS         179.15    177.20     1,187      0.00      0.00      0.00      0.00
Gabriel India Ltd.                 GABRIEL       397.70    403.60     5,733      0.00      0.00      0.00      0.00
Gensol Engineering Ltd.            GENSOL        767.05    768.80     2,956      0.00      0.00      0.00      0.00
Genus Power Infrastructures Lt     GENUSPOWER    228.05    231.15     5,864      0.00      0.00      0.00      0.00
Hariom Pipe Industries Ltd.        HARIOMPIPE    635.45    634.15     1,756      0.00      0.00      0.00      0.00

HBL Power Systems Ltd.             HBLPOWER      445.80    443.30    12,359      0.00      0.00      0.00      0.00
Hindustan Construction Company     HCC            28.60     29.05     4,321      0.00      0.00      0.00      0.00
Hind Rectifiers Ltd.               HIRECT        554.70    551.95       943      0.00      0.00      0.00      0.00
Hi-Tech Pipes Ltd.                 HITECH        112.25     99.95     1,538      0.00      0.00      0.00      0.00
HPL Electric & Power Ltd.          HPL           210.40    214.15     1,354      0.00      0.00      0.00      0.00

Indo Count Industries Ltd.         ICIL          295.35    293.15     5,842      0.00      0.00      0.00      0.00
IFGL Refractories Ltd.             IFGLEXPOR     789.50    767.40     2,859      0.00      0.00      0.00      0.00
IIFL Securities Ltd.               IIFLSEC       145.60    137.40     4,520      0.00      0.00      0.00      0.00
IKIO Lighting Ltd.                 IKIO          335.80    342.90     2,594      0.00      0.00      0.00      0.00

Indraprastha Medical Corporati     INDRAMEDCO    178.65    179.55     1,645      0.00      0.00      0.00      0.00

Inox Wind Ltd.                     INOXWIND      466.15    453.25    15,183      0.00      0.00      0.00      0.00
JK Lakshmi Cement Ltd.             JKLAKSHMI     885.55    870.05    10,372      0.00      0.00      0.00      0.00
JK Tyre & Industries Ltd.          JKTYRE        377.40    383.30     9,290      0.00      0.00      0.00      0.00
Jaiprakash Associates Ltd.         JPASSOCIAT     20.85     21.10     5,118      0.00      0.00      0.00      0.00
Jaiprakash Power Ventures Ltd.     JPPOWER        13.95     13.25     9,519      0.00      0.00      0.00      0.00

Sai Kalamandir                     KALAMANDIR    274.90    277.50     4,219      0.00      0.00      0.00      0.00
Kesoram Industries Ltd.            KESORAMIND    168.95    167.05     5,241      0.00      0.00      0.00      0.00
KFin Technologies Ltd.             KFINTECH      502.60    491.85     8,555      0.00      0.00      0.00      0.00
KPI Green Energy Ltd.              KPIGREEN     1331.10   1342.40     4,999      0.00      0.00      0.00      0.00
LT Foods Ltd.                      LTFOODS       203.45    200.65     7,080      0.00      0.00      0.00      0.00

Lumax Auto Technologies Ltd.       LUMAXTECH     389.15    384.25     2,658      0.00      0.00      0.00      0.00
Man Industries (India) Ltd.        MANINDS       251.85    251.10     1,508      0.00      0.00      0.00      0.00
Marine Electricals (India) Ltd     MARINE         99.50     97.75     1,289      0.00      0.00      0.00      0.00
Marksans Pharma Ltd.               MARKSANS      158.70    160.05     7,214      0.00      0.00      0.00      0.00
MOIL Ltd.                          MOIL          305.90    306.30     6,231      0.00      0.00      0.00      0.00

Manoj Vaibhav                      MVGJL         334.75    328.70     1,635      0.00      0.00      0.00      0.00
Neuland Laboratories Ltd.          NEULANDLAB   5329.70   5115.50     6,844      0.00      0.00      0.00      0.00
Newgen Software Technologies L     NEWGEN       1509.55   1438.55    10,582      0.00      0.00      0.00      0.00
Parag Milk Foods Ltd.              PARAGMILK     236.55    237.35     2,775      0.00      0.00      0.00      0.00
Peninsula Land Ltd.                PENINLAND      51.80     50.30     1,510      0.00      0.00      0.00      0.00

PTC India Financial Services L     PFS            41.85     42.50     2,682      0.00      0.00      0.00      0.00
Pokarna Ltd.                       POKARNA       490.00    481.75     1,519      0.00      0.00      0.00      0.00
Premier Explosives Ltd.            PREMEXPLN    1612.90   1603.20     1,748      0.00      0.00      0.00      0.00
Prism Johnson Ltd.                 PRSMJOHNSN    182.00    181.00     9,179      0.00      0.00      0.00      0.00
Ramky Infrastructure Ltd.          RAMKY         789.85    796.30     5,439      0.00      0.00      0.00      0.00

RateGain Travel Technologies L     RATEGAIN      730.10    740.20     8,699      0.00      0.00      0.00      0.00
Repco Home Finance Ltd.            REPCOHOME     396.75    396.75     2,482      0.00      0.00      0.00      0.00
RPG Life Sciences Ltd.             RPGLIFE      1369.05   1363.40     2,275      0.00      0.00      0.00      0.00
Sadhana Nitro Chem Ltd.            SADHNANIQ      86.75     85.80     2,144      0.00      0.00      0.00      0.00
Sanghvi Movers Ltd.                SANGHVIMOV    825.65    835.60     3,581      0.00      0.00      0.00      0.00

Satin Creditcare Network Ltd.      SATIN         242.10    252.75     2,677      0.00      0.00      0.00      0.00
Som Distilleries Breweries & W     SDBL          288.95    291.65     2,238      0.00      0.00      0.00      0.00
Senco Gold Ltd.                    SENCO         722.30    727.55     5,612      0.00      0.00      0.00      0.00
SEPC Ltd.                          SEPC           20.85     21.00     2,946      0.00      0.00      0.00      0.00
Shriram Pistons & Rings Ltd        SHRIPISTON   1341.30   1277.45     5,908      0.00      0.00      0.00      0.00

Shriram Properties Ltd.            SHRIRAMPPS    120.55    119.05     2,052      0.00      0.00      0.00      0.00
Skipper Ltd.                       SKIPPER       224.95    225.85     2,315      0.00      0.00      0.00      0.00
Somany Ceramics Ltd.               SOMANYCERA    716.95    726.75     3,027      0.00      0.00      0.00      0.00
Spandana Sphoorty Financial Lt     SPANDANA     1029.70   1036.55     7,347      0.00      0.00      0.00      0.00
Transport Corporation Of India     TCI           818.15    816.75     6,352      0.00      0.00      0.00      0.00

TD Power Systems Ltd.              TDPOWERSYS    266.00    267.55     4,141      0.00      0.00      0.00      0.00
Thomas Cook (India) Ltd.           THOMASCOOK    140.30    139.80     6,576      0.00      0.00      0.00      0.00
Transformers & Rectifiers (Ind     TRIL          217.40    224.05     3,117      0.00      0.00      0.00      0.00
TV18 Broadcast Ltd.                TV18BRDCST     52.15     51.00     8,947      0.00      0.00      0.00      0.00
Vijaya Diagnostic Centre Ltd.      VIJAYA        630.80    640.90     6,458      0.00      0.00      0.00      0.00

Zaggle Prepaid                     ZAGGLE        221.75    224.45     2,709      0.00      0.00      0.00      0.00
Zee Media Corporation Ltd.         ZEEMEDIA       15.40     15.70       959      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

         Top deliveries mktcap below 1000 cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


20 Microns Ltd.                    20MICRONS     188.95    189.45       667      0.00      0.00      0.00      0.00
Kilburn Engineering Ltd.           522101        281.70    280.80     1,067    282.14    278.92    255.32    179.65
Nile Ltd.                          530129        874.75    882.10       262    878.40    881.02    844.51    735.64
Ceinsys Tech Ltd.                  538734        351.45    356.30       542    356.46    356.08    336.10    251.65
RMC Switchgears Ltd.               540358        587.75    578.75       608    584.15    586.85    603.08    515.17

Khazanchi Jewellers Ltd            543953        274.00    273.15       678    274.50    276.12    264.36    207.34
Bondada Engineering Limited        543971        379.75    391.75       817    395.87    397.40    359.02    242.00
Annapurna Swadisht Ltd.            ANNAPURNA     319.50    323.80       556    331.49    334.41    326.04    278.64
Arihant Superstructures Ltd.       ARIHANTSUP    269.05    261.55     1,118      0.00      0.00      0.00      0.00
Chembond Chemicals Ltd.            CHEMBOND      546.40    550.45       733      0.00      0.00      0.00      0.00

Dharmaj Crop Guard Ltd.            DHARMAJ       263.25    258.45       900      0.00      0.00      0.00      0.00
Global Education Ltd.              GLOBAL        311.00    308.75       633      0.00      0.00      0.00      0.00
Indo Tech Transformers Ltd.        INDOTECH      629.05    599.10       668      0.00      0.00      0.00      0.00
Kapston Services Ltd.              KAPSTON       246.85    235.10       250      0.00      0.00      0.00      0.00
Kothari Petrochemicals Ltd.        KOTHARIPET    152.45    147.55       897      0.00      0.00      0.00      0.00

Magson Retail & Distribution L     MAGSON        134.80    134.75       106    129.73    125.84    115.22     95.25
MBL Infrastructure Ltd.            MBLINFRA       46.15     45.25       477      0.00      0.00      0.00      0.00
Modison Ltd.                       MODISONLTD    130.55    132.20       423      0.00      0.00      0.00      0.00
NDR Auto Components Ltd.           NDRAUTO       778.25    747.00       925      0.00      0.00      0.00      0.00

Pyramid Technoplast Limited        PYRAMID       195.85    192.90       722      0.00      0.00      0.00      0.00

Semac Consultants Ltd              SEMAC        2303.00   2350.00       708      0.00      0.00      0.00      0.00
Sky Gold Ltd.                      SKYGOLD      1003.90    956.10     1,079      0.00      0.00      0.00      0.00
Venus Remedies Ltd.                VENUSREM      395.80    389.95       527      0.00      0.00      0.00      0.00
Walchandnagar Industries Ltd.      WALCHANNAG    196.95    187.60       905      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

In [25]:
check_stock = ['inspirisys','coalindia','wockpharma', 'imagicaa','stltech','cub','sagcem','sapphire']
list_process_new(check_stock, "temp check")

temp check
Company Name: Inspirisys Solutions Ltd. (NSE Code: INSPIRISYS, BSE Code: 532774, Mktcap:338, Networth:-9)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           5,181           3,753           8,934      71.45
   231010           7,170           1,545           8,715      63.30
   230810           1,354           1,729           3,083      78.45
   230420           6,390           2,960           9,350      54.15
   190124             932               2             934      56.00

==================================================


Company Name: Coal India Ltd. (NSE Code: COALINDIA, BSE Code: 533278, Mktcap:225,618, Networth:69,686)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       2,305,726          46,430       2,352,156     312.40
   231010       8,636,371         172,611       8,808,982     303.25
   230810       5,663,735          71,336       5,735,071     234.90
   230420       1,019,622          81,105       1,100,727     229.55
   190124       1,553,925          53,657       1,607,582     223.85

==================================================


Company Name: Wockhardt Ltd. (NSE Code: WOCKPHARMA, BSE Code: 532300, Mktcap:6,046, Networth:3,125)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         267,803          24,348         292,151     244.15
   231010         140,470          19,106         159,576     230.85
   230810         545,482          42,393         587,875     256.55
   230420         246,988          32,599         279,587     173.75
   190124         128,109          15,878         143,987     483.60

==================================================


Company Name: Imagicaaworld Entertainment Lt (NSE Code: IMAGICAA, BSE Code: 539056, Mktcap:2,855, Networth:785)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         519,217          62,356         581,573      48.80
   231010         497,507          15,653         513,160      50.50
   230810       1,548,161         144,637       1,692,798      57.25
   230420         242,380          30,466         272,846      44.50
   190124               0          33,404          33,404       9.82

==================================================


Company Name: Sterlite Technologies Ltd. (NSE Code: STLTECH, BSE Code: 532374, Mktcap:5,742, Networth:2,136)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       1,484,941         108,245       1,593,186     165.00
   231010         267,913          30,865         298,778     155.95
   230810       1,011,244          63,444       1,074,688     154.55
   230420         219,011          22,578         241,589     158.25
   190124               0          92,456          92,456     290.10

==================================================


Company Name: City Union Bank Ltd. (NSE Code: CUB, BSE Code: 532210, Mktcap:11,021, Networth:7,457)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       1,173,757       1,064,573       2,238,330     136.45
   231010       8,775,549         865,242       9,640,791     134.75
   230810         596,648          33,856         630,504     132.65
   230420       2,017,893         185,579       2,203,472     133.20
   190124         754,537           7,277         761,814     190.05

==================================================


Company Name: Sagar Cements Ltd. (NSE Code: SAGCEM, BSE Code: 502090, Mktcap:3,382, Networth:1,582)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         394,490          48,561         443,051     258.30
   231010          27,615           4,930          32,545     232.80
   230810         142,502          11,929         154,431     242.50
   230420          35,646           2,675          38,321     194.05
   190124             218               1             219     625.30

==================================================


Company Name: Sapphire Foods India Ltd. (NSE Code: SAPPHIRE, BSE Code: 543397, Mktcap:9,095, Networth:1,311)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          51,838             273          52,111    1408.15
   231010          92,188             782          92,970    1406.40
   230810          18,406             490          18,896    1362.70
   230420          33,560             317          33,877    1194.85

==================================================

In [85]:
from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def create_table_with_header(df, add_column_names=False, table_width=None):
    """create a table with header and data"""
    table_data = [df.columns.tolist()] + df.values.tolist()
        
    style = [
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),  # Left align first column
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),  # Right align remaining columns
    ]

    t = Table(table_data, repeatRows=1, colWidths=[100, 80, 80, 80, 60])
    column_header_style = [('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ]
    
    t.setStyle(column_header_style)
    t.setStyle(style)
    
    # Remove table borders
    t.setStyle([('LINEBELOW', (0, 0), (-1, 0), 0, colors.white),  # Hide line below header
                ('GRID', (0, 0), (-1, -1), 0, colors.white)])      # Hide grid lines
    
    return t

def add_headers_and_footers(canvas, doc):
    """Add header and footer here"""
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    footer_style = getSampleStyleSheet()['Normal']
    footer_style.alignment = 1  # 0=Left, 1=Center, 2=Right

    footer = Paragraph(text, footer_style)
    w, h = footer.wrap(doc.width, doc.bottomMargin)
    footer.drawOn(canvas, doc.leftMargin, doc.bottomMargin - h)

    # Change title text color to white for pages after the first one
    if page_num > 1:
        title_style = getSampleStyleSheet()['Title']
        title_style.textColor = colors.white

def list_process_to_pdf(list_name, header, output_path):
    left_margin = 20
    right_margin = 20
    top_margin = 5
    bottom_margin = 20  # Add a bottom margin
    page_width = A4[0]  # Get width from letter page size
    page_height = A4[1] - top_margin - bottom_margin  # Adjust height for margins

    # Create a SimpleDocTemplate with adjusted page size and margins
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=(page_width, page_height),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin
    )

    # Create a list to hold all elements
    elements = []
    for company in list_name:
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]

        if not company_data.empty:
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10, ema20, ema50, ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"

            mktcap_value = get_mktcap(nse_code)

            # adding company info to pdf
            txt = f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap: {mktcap_value[0]:,.0f})"
            styles = getSampleStyleSheet()
            h2_style = styles['Normal']
            h2_style.fontSize = 11
            h2_style.Name = 'Arial'
            h2_style.bold = True
            h2_style.alignment = 0 
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
            txt =f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}"

            h2_style.fontSize = 10
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])

            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            formatted_data_str = formatted_data.to_string(index=False, col_space={'Date': 9, 'NSE_Delivery': 15, 'BSE_Delivery': 15,
                                                                                   'Total_Delivery': 15, 'Price': 10})
            table_width = doc.width - doc.leftMargin - doc.rightMargin
            table = create_table_with_header(formatted_data, add_column_names=True, table_width=table_width)
            elements.append(table)
            # adding space
            elements.extend([Spacer(1, 24)])
        else:
            txt=f"No data found for {company}\n"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
        
    doc.build(elements, onFirstPage=add_headers_and_footers, onLaterPages=add_headers_and_footers)

In [86]:
list_process_to_pdf(check_stock, "temp check", "output_a4_spacing_1_reduced_testing.pdf")

In [102]:
# Remove duplicates and sort the list in-place
#my_list = list(set(my_list))
#my_list.sort()

list_below_1000 = ['522101','530129','538734','540358','540358','543953','543971','20microns','annapurna',
                   'arihantsup','chembond','dharmaj','global','indotech','kapston','kotharipet','magson',
                   'mblinfra','modisonltd','ndrauto','pyramid','semac','skygold','venusrem','walchannag']

list_below_1000 = list(set(list_below_1000))
list_below_1000.sort()


list_1k_10k = ['531112','542669','543620','anantraj','anup','apollo','arvind','arvindfasn','bajajhind','bancoindia',
               'bclind','bluejet','cignititec','cupid','dbrealty','diamondyd','dollar','electcast','emil','focus',
               'forcemot','gabriel','gensol','genuspower','hariompipe','hblpower','hcc','hirect','hitech','hpl',
               'icil','ifglexpor','iiflsec','ikio','inoxwind','jklakshmi','jktyre','jpassociat','jppower','kalamandir',
               'kesoramind','kfintech','kpigreen','ltfoods','lumaxtech','maninds','marine','moil','mvgjl','neulandlab',
               'newgen','paragmilk','peninland','pfs','pokarna','premexpln','prsmjohnsn','ramky','rategain','repcohome',
               'rpglife','sadhnaniq','sanghvimov','satin','sdbl','senco','sepc','shripiston','shrirampps','skipper',
               'somanycera','spandana','tci','tdpowersys','thomascook','tril','tv18brdcst','vijaya','zaggle',
               'zeemedia','awhcl','indramedco','marksans']

list_1k_10k = list(set(list_1k_10k))
list_1k_10k.sort()

list_above_10k = ['adanipower','amber','angelone','bikaji','bluestarco','brigade','bse','cdsl','cello','concordbio',
                  'creditacc','elecon','idea','jindalsaw','jkcement','jwl','kpittech','l&tfh','lalpathlab','lodha',
                  'mcx','patanjali','paytm','phoenixltd','piind','poonawalla','pplpharma','prestige','radico',
                  'recltd','rkforge','shriramfin','solarinds','sonatsoftw','suzlon','tatamotors','titagarh','trent',
                  'unionbank','welspunind','zomato','medanta','swanenergy','welcorp']

list_above_10k = list(set(list_above_10k))
list_above_10k.sort()